// <auto-generated>
// DO NOT EDIT. Generated by `reference generate` from GPUI Kit's default
// component icons (crates/assets/default-icons.txt).
// </auto-generated>
namespace AvaloniaUIKit;

/// <summary>
/// GPUI Kit's IconName (crates/component/src/icon.rs): the icons GPUI Kit ships
/// for its components. <see cref="Icon.Kind"/> draws one; its geometry is the
/// resource <see cref="IconNames.ResourceKey"/> names.
/// </summary>
public enum IconName
{
    /// <summary>icons/a-large-small.svg</summary>
    ALargeSmall,
    /// <summary>icons/arrow-down.svg</summary>
    ArrowDown,
    /// <summary>icons/arrow-left.svg</summary>
    ArrowLeft,
    /// <summary>icons/arrow-right.svg</summary>
    ArrowRight,
    /// <summary>icons/arrow-up.svg</summary>
    ArrowUp,
    /// <summary>icons/asterisk.svg</summary>
    Asterisk,
    /// <summary>icons/ban.svg</summary>
    Ban,
    /// <summary>icons/battery.svg</summary>
    Battery,
    /// <summary>icons/battery-charging.svg</summary>
    BatteryCharging,
    /// <summary>icons/battery-full.svg</summary>
    BatteryFull,
    /// <summary>icons/battery-low.svg</summary>
    BatteryLow,
    /// <summary>icons/battery-medium.svg</summary>
    BatteryMedium,
    /// <summary>icons/battery-warning.svg</summary>
    BatteryWarning,
    /// <summary>icons/bell.svg</summary>
    Bell,
    /// <summary>icons/book-open.svg</summary>
    BookOpen,
    /// <summary>icons/bot.svg</summary>
    Bot,
    /// <summary>icons/building-2.svg</summary>
    Building2,
    /// <summary>icons/calendar.svg</summary>
    Calendar,
    /// <summary>icons/case-sensitive.svg</summary>
    CaseSensitive,
    /// <summary>icons/chart-pie.svg</summary>
    ChartPie,
    /// <summary>icons/check.svg</summary>
    Check,
    /// <summary>icons/chevron-down.svg</summary>
    ChevronDown,
    /// <summary>icons/chevron-left.svg</summary>
    ChevronLeft,
    /// <summary>icons/chevron-right.svg</summary>
    ChevronRight,
    /// <summary>icons/chevron-up.svg</summary>
    ChevronUp,
    /// <summary>icons/chevrons-up-down.svg</summary>
    ChevronsUpDown,
    /// <summary>icons/circle-alert.svg</summary>
    CircleAlert,
    /// <summary>icons/circle-check.svg</summary>
    CircleCheck,
    /// <summary>icons/circle-user.svg</summary>
    CircleUser,
    /// <summary>icons/circle-x.svg</summary>
    CircleX,
    /// <summary>icons/close.svg</summary>
    Close,
    /// <summary>icons/copy.svg</summary>
    Copy,
    /// <summary>icons/cpu.svg</summary>
    Cpu,
    /// <summary>icons/dash.svg</summary>
    Dash,
    /// <summary>icons/delete.svg</summary>
    Delete,
    /// <summary>icons/ellipsis.svg</summary>
    Ellipsis,
    /// <summary>icons/ellipsis-vertical.svg</summary>
    EllipsisVertical,
    /// <summary>icons/external-link.svg</summary>
    ExternalLink,
    /// <summary>icons/eye.svg</summary>
    Eye,
    /// <summary>icons/eye-off.svg</summary>
    EyeOff,
    /// <summary>icons/file.svg</summary>
    File,
    /// <summary>icons/file-text.svg</summary>
    FileText,
    /// <summary>icons/folder.svg</summary>
    Folder,
    /// <summary>icons/folder-closed.svg</summary>
    FolderClosed,
    /// <summary>icons/folder-open.svg</summary>
    FolderOpen,
    /// <summary>icons/frame.svg</summary>
    Frame,
    /// <summary>icons/gallery-vertical-end.svg</summary>
    GalleryVerticalEnd,
    /// <summary>icons/github.svg</summary>
    Github,
    /// <summary>icons/globe.svg</summary>
    Globe,
    /// <summary>icons/hard-drive.svg</summary>
    HardDrive,
    /// <summary>icons/heart.svg</summary>
    Heart,
    /// <summary>icons/heart-off.svg</summary>
    HeartOff,
    /// <summary>icons/inbox.svg</summary>
    Inbox,
    /// <summary>icons/info.svg</summary>
    Info,
    /// <summary>icons/inspector.svg</summary>
    Inspector,
    /// <summary>icons/layout-dashboard.svg</summary>
    LayoutDashboard,
    /// <summary>icons/loader.svg</summary>
    Loader,
    /// <summary>icons/loader-circle.svg</summary>
    LoaderCircle,
    /// <summary>icons/map.svg</summary>
    Map,
    /// <summary>icons/maximize.svg</summary>
    Maximize,
    /// <summary>icons/memory-stick.svg</summary>
    MemoryStick,
    /// <summary>icons/menu.svg</summary>
    Menu,
    /// <summary>icons/mic.svg</summary>
    Mic,
    /// <summary>icons/minimize.svg</summary>
    Minimize,
    /// <summary>icons/minus.svg</summary>
    Minus,
    /// <summary>icons/moon.svg</summary>
    Moon,
    /// <summary>icons/network.svg</summary>
    Network,
    /// <summary>icons/palette.svg</summary>
    Palette,
    /// <summary>icons/panel-bottom.svg</summary>
    PanelBottom,
    /// <summary>icons/panel-bottom-open.svg</summary>
    PanelBottomOpen,
    /// <summary>icons/panel-left.svg</summary>
    PanelLeft,
    /// <summary>icons/panel-left-close.svg</summary>
    PanelLeftClose,
    /// <summary>icons/panel-left-open.svg</summary>
    PanelLeftOpen,
    /// <summary>icons/panel-right.svg</summary>
    PanelRight,
    /// <summary>icons/panel-right-close.svg</summary>
    PanelRightClose,
    /// <summary>icons/panel-right-open.svg</summary>
    PanelRightOpen,
    /// <summary>icons/pause.svg</summary>
    Pause,
    /// <summary>icons/play.svg</summary>
    Play,
    /// <summary>icons/plus.svg</summary>
    Plus,
    /// <summary>icons/redo.svg</summary>
    Redo,
    /// <summary>icons/redo-2.svg</summary>
    Redo2,
    /// <summary>icons/refresh-cw.svg</summary>
    RefreshCw,
    /// <summary>icons/replace.svg</summary>
    Replace,
    /// <summary>icons/resize-corner.svg</summary>
    ResizeCorner,
    /// <summary>icons/rotate-cw.svg</summary>
    RotateCw,
    /// <summary>icons/search.svg</summary>
    Search,
    /// <summary>icons/settings.svg</summary>
    Settings,
    /// <summary>icons/settings-2.svg</summary>
    Settings2,
    /// <summary>icons/sort-ascending.svg</summary>
    SortAscending,
    /// <summary>icons/sort-descending.svg</summary>
    SortDescending,
    /// <summary>icons/square.svg</summary>
    Square,
    /// <summary>icons/square-terminal.svg</summary>
    SquareTerminal,
    /// <summary>icons/star.svg</summary>
    Star,
    /// <summary>icons/star-fill.svg</summary>
    StarFill,
    /// <summary>icons/star-off.svg</summary>
    StarOff,
    /// <summary>icons/sun.svg</summary>
    Sun,
    /// <summary>icons/thumbs-down.svg</summary>
    ThumbsDown,
    /// <summary>icons/thumbs-up.svg</summary>
    ThumbsUp,
    /// <summary>icons/triangle-alert.svg</summary>
    TriangleAlert,
    /// <summary>icons/undo.svg</summary>
    Undo,
    /// <summary>icons/undo-2.svg</summary>
    Undo2,
    /// <summary>icons/user.svg</summary>
    User,
    /// <summary>icons/window-close.svg</summary>
    WindowClose,
    /// <summary>icons/window-maximize.svg</summary>
    WindowMaximize,
    /// <summary>icons/window-minimize.svg</summary>
    WindowMinimize,
    /// <summary>icons/window-restore.svg</summary>
    WindowRestore,
}

/// <summary>The resources of <see cref="IconName"/>s.</summary>
public static class IconNames
{
    /// <summary>The key of the icon's geometry resource (Themes/Icons/Lucide.g.axaml).</summary>
    public static string ResourceKey(this IconName name) => name switch
    {
        IconName.ALargeSmall => "UIKit.Icon.ALargeSmall",
        IconName.ArrowDown => "UIKit.Icon.ArrowDown",
        IconName.ArrowLeft => "UIKit.Icon.ArrowLeft",
        IconName.ArrowRight => "UIKit.Icon.ArrowRight",
        IconName.ArrowUp => "UIKit.Icon.ArrowUp",
        IconName.Asterisk => "UIKit.Icon.Asterisk",
        IconName.Ban => "UIKit.Icon.Ban",
        IconName.Battery => "UIKit.Icon.Battery",
        IconName.BatteryCharging => "UIKit.Icon.BatteryCharging",
        IconName.BatteryFull => "UIKit.Icon.BatteryFull",
        IconName.BatteryLow => "UIKit.Icon.BatteryLow",
        IconName.BatteryMedium => "UIKit.Icon.BatteryMedium",
        IconName.BatteryWarning => "UIKit.Icon.BatteryWarning",
        IconName.Bell => "UIKit.Icon.Bell",
        IconName.BookOpen => "UIKit.Icon.BookOpen",
        IconName.Bot => "UIKit.Icon.Bot",
        IconName.Building2 => "UIKit.Icon.Building2",
        IconName.Calendar => "UIKit.Icon.Calendar",
        IconName.CaseSensitive => "UIKit.Icon.CaseSensitive",
        IconName.ChartPie => "UIKit.Icon.ChartPie",
        IconName.Check => "UIKit.Icon.Check",
        IconName.ChevronDown => "UIKit.Icon.ChevronDown",
        IconName.ChevronLeft => "UIKit.Icon.ChevronLeft",
        IconName.ChevronRight => "UIKit.Icon.ChevronRight",
        IconName.ChevronUp => "UIKit.Icon.ChevronUp",
        IconName.ChevronsUpDown => "UIKit.Icon.ChevronsUpDown",
        IconName.CircleAlert => "UIKit.Icon.CircleAlert",
        IconName.CircleCheck => "UIKit.Icon.CircleCheck",
        IconName.CircleUser => "UIKit.Icon.CircleUser",
        IconName.CircleX => "UIKit.Icon.CircleX",
        IconName.Close => "UIKit.Icon.Close",
        IconName.Copy => "UIKit.Icon.Copy",
        IconName.Cpu => "UIKit.Icon.Cpu",
        IconName.Dash => "UIKit.Icon.Dash",
        IconName.Delete => "UIKit.Icon.Delete",
        IconName.Ellipsis => "UIKit.Icon.Ellipsis",
        IconName.EllipsisVertical => "UIKit.Icon.EllipsisVertical",
        IconName.ExternalLink => "UIKit.Icon.ExternalLink",
        IconName.Eye => "UIKit.Icon.Eye",
        IconName.EyeOff => "UIKit.Icon.EyeOff",
        IconName.File => "UIKit.Icon.File",
        IconName.FileText => "UIKit.Icon.FileText",
        IconName.Folder => "UIKit.Icon.Folder",
        IconName.FolderClosed => "UIKit.Icon.FolderClosed",
        IconName.FolderOpen => "UIKit.Icon.FolderOpen",
        IconName.Frame => "UIKit.Icon.Frame",
        IconName.GalleryVerticalEnd => "UIKit.Icon.GalleryVerticalEnd",
        IconName.Github => "UIKit.Icon.Github",
        IconName.Globe => "UIKit.Icon.Globe",
        IconName.HardDrive => "UIKit.Icon.HardDrive",
        IconName.Heart => "UIKit.Icon.Heart",
        IconName.HeartOff => "UIKit.Icon.HeartOff",
        IconName.Inbox => "UIKit.Icon.Inbox",
        IconName.Info => "UIKit.Icon.Info",
        IconName.Inspector => "UIKit.Icon.Inspector",
        IconName.LayoutDashboard => "UIKit.Icon.LayoutDashboard",
        IconName.Loader => "UIKit.Icon.Loader",
        IconName.LoaderCircle => "UIKit.Icon.LoaderCircle",
        IconName.Map => "UIKit.Icon.Map",
        IconName.Maximize => "UIKit.Icon.Maximize",
        IconName.MemoryStick => "UIKit.Icon.MemoryStick",
        IconName.Menu => "UIKit.Icon.Menu",
        IconName.Mic => "UIKit.Icon.Mic",
        IconName.Minimize => "UIKit.Icon.Minimize",
        IconName.Minus => "UIKit.Icon.Minus",
        IconName.Moon => "UIKit.Icon.Moon",
        IconName.Network => "UIKit.Icon.Network",
        IconName.Palette => "UIKit.Icon.Palette",
        IconName.PanelBottom => "UIKit.Icon.PanelBottom",
        IconName.PanelBottomOpen => "UIKit.Icon.PanelBottomOpen",
        IconName.PanelLeft => "UIKit.Icon.PanelLeft",
        IconName.PanelLeftClose => "UIKit.Icon.PanelLeftClose",
        IconName.PanelLeftOpen => "UIKit.Icon.PanelLeftOpen",
        IconName.PanelRight => "UIKit.Icon.PanelRight",
        IconName.PanelRightClose => "UIKit.Icon.PanelRightClose",
        IconName.PanelRightOpen => "UIKit.Icon.PanelRightOpen",
        IconName.Pause => "UIKit.Icon.Pause",
        IconName.Play => "UIKit.Icon.Play",
        IconName.Plus => "UIKit.Icon.Plus",
        IconName.Redo => "UIKit.Icon.Redo",
        IconName.Redo2 => "UIKit.Icon.Redo2",
        IconName.RefreshCw => "UIKit.Icon.RefreshCw",
        IconName.Replace => "UIKit.Icon.Replace",
        IconName.ResizeCorner => "UIKit.Icon.ResizeCorner",
        IconName.RotateCw => "UIKit.Icon.RotateCw",
        IconName.Search => "UIKit.Icon.Search",
        IconName.Settings => "UIKit.Icon.Settings",
        IconName.Settings2 => "UIKit.Icon.Settings2",
        IconName.SortAscending => "UIKit.Icon.SortAscending",
        IconName.SortDescending => "UIKit.Icon.SortDescending",
        IconName.Square => "UIKit.Icon.Square",
        IconName.SquareTerminal => "UIKit.Icon.SquareTerminal",
        IconName.Star => "UIKit.Icon.Star",
        IconName.StarFill => "UIKit.Icon.StarFill",
        IconName.StarOff => "UIKit.Icon.StarOff",
        IconName.Sun => "UIKit.Icon.Sun",
        IconName.ThumbsDown => "UIKit.Icon.ThumbsDown",
        IconName.ThumbsUp => "UIKit.Icon.ThumbsUp",
        IconName.TriangleAlert => "UIKit.Icon.TriangleAlert",
        IconName.Undo => "UIKit.Icon.Undo",
        IconName.Undo2 => "UIKit.Icon.Undo2",
        IconName.User => "UIKit.Icon.User",
        IconName.WindowClose => "UIKit.Icon.WindowClose",
        IconName.WindowMaximize => "UIKit.Icon.WindowMaximize",
        IconName.WindowMinimize => "UIKit.Icon.WindowMinimize",
        IconName.WindowRestore => "UIKit.Icon.WindowRestore",
        _ => throw new ArgumentOutOfRangeException(nameof(name)),
    };

    /// <summary>
    /// The opacity of the icon's faint part (the resource with ".Faint" after
    /// the key), or 0 when it has none.
    /// </summary>
    internal static double FaintOpacity(this IconName name) => name switch
    {
        IconName.SortAscending => 0.2,
        IconName.SortDescending => 0.2,
        _ => 0,
    };
}
