/**
 * The icons the theme bundles, read at build time for the Icons page: each
 * `UIKit.Icon.*` geometry (src/AvaloniaUIKit/Themes/Icons/Lucide.g.axaml),
 * the `IconName` that draws it with `uikit:Icon` and the file GPUI Kit ships
 * it as (Controls/IconName.g.cs). Both files are generated by
 * `reference generate`, so the page shows exactly what the theme draws.
 */
import iconNamesSource from "../../../src/AvaloniaUIKit/Controls/IconName.g.cs?raw"
import lucideXaml from "../../../src/AvaloniaUIKit/Themes/Icons/Lucide.g.axaml?raw"
import { kebab } from "./demos"

export interface BundledIcon {
  /** The resource key without its prefix: `UIKit.Icon.<name>`. */
  name: string
  key: string
  /** The `IconName` that draws it with `uikit:Icon`; none for the icons only the themes draw. */
  kind?: string
  /** The SVG GPUI Kit ships it as, without `.svg` (`chevron-down`). */
  file: string
  /**
   * The geometry as SVG path data in the 24×24 icon box. Avalonia's path
   * markup is SVG's, after the fill rule (`F1`, nonzero).
   */
  path: string
  fillRule: "nonzero" | "evenodd"
  /** A two-tone icon's faint part, which `uikit:Icon` paints under it at its opacity. */
  faint?: { path: string; opacity: number }
}

const prefix = "UIKit.Icon."

const geometries = new Map(
  [
    ...lucideXaml.matchAll(
      /<StreamGeometry x:Key="UIKit\.Icon\.([\w.]+)">F([01]) ([^<]+)<\/StreamGeometry>/g
    ),
  ].map(([, name, rule, path]) => [
    name,
    {
      path: path.trim(),
      fillRule: rule === "1" ? ("nonzero" as const) : ("evenodd" as const),
    },
  ])
)

/** `IconName` variants by the key they draw, with their files (`/// <summary>icons/<file>.svg</summary>`). */
const files = new Map(
  [
    ...iconNamesSource.matchAll(
      /\/\/\/ <summary>icons\/([\w-]+)\.svg<\/summary>\s+(\w+),/g
    ),
  ].map(([, file, kind]) => [kind, file])
)
const kinds = new Map(
  [
    ...iconNamesSource.matchAll(/IconName\.(\w+) => "UIKit\.Icon\.([\w.]+)"/g),
  ].map(([, kind, name]) => [name, kind])
)
const faintOpacity = new Map(
  [
    ...(iconNamesSource.split("FaintOpacity")[1] ?? "").matchAll(
      /IconName\.(\w+) => ([\d.]+),/g
    ),
  ].map(([, kind, opacity]) => [kind, Number(opacity)])
)

/** Every bundled icon, by name. */
export const bundledIcons: BundledIcon[] = [...geometries]
  .filter(([name]) => !name.endsWith(".Faint"))
  .map(([name, geometry]) => {
    const kind = kinds.get(name)
    const faint = geometries.get(`${name}.Faint`)
    const opacity = kind ? faintOpacity.get(kind) : undefined
    return {
      name,
      key: `${prefix}${name}`,
      kind,
      file: (kind && files.get(kind)) ?? kebab(name),
      ...geometry,
      faint: faint && opacity ? { path: faint.path, opacity } : undefined,
    }
  })
  .sort((a, b) => a.name.localeCompare(b.name, "en"))

if (bundledIcons.length === 0) {
  throw new Error("No icons in src/AvaloniaUIKit/Themes/Icons/Lucide.g.axaml")
}

/**
 * The sizes the theme's PathIcon has (Themes/Base/PathIcon.axaml): medium is
 * the default, the others are classes.
 */
export const iconSizes = [
  { name: "xsmall", px: 12 },
  { name: "small", px: 14 },
  { name: "medium", px: 16 },
  { name: "large", px: 24 },
] as const

/**
 * The colors the Icons page offers for `Foreground`: the theme's resources
 * that the site also has, so the preview shows them in the site's theme.
 * Without a resource the icon takes the Foreground it inherits.
 */
export const iconColors = [
  { name: "Default", resource: undefined, css: "var(--foreground)" },
  { name: "Muted", resource: "UIKit.MutedForeground", css: "var(--muted-foreground)" },
  { name: "Primary", resource: "UIKit.Primary", css: "var(--primary)" },
  { name: "Danger", resource: "UIKit.Danger", css: "var(--destructive)" },
  { name: "Warning", resource: "UIKit.Warning", css: "var(--warning)" },
  { name: "Success", resource: "UIKit.Success", css: "var(--success)" },
] as const
