// <auto-generated/>
// Generated by `bun sites/scripts/demo-registry.ts` from Demos/**/*.axaml. Do not edit.
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaloniaUIKit.Demos;

public sealed partial class AccordionBorderless : UserControl
{
    public AccordionBorderless() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AccordionDemo : UserControl
{
    public AccordionDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AccordionIcons : UserControl
{
    public AccordionIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AccordionSizes : UserControl
{
    public AccordionSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AlertBanner : UserControl
{
    public AlertBanner() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AlertDemo : UserControl
{
    public AlertDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AlertSizes : UserControl
{
    public AlertSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AlertVariants : UserControl
{
    public AlertVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AvatarDemo : UserControl
{
    public AvatarDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AvatarGroups : UserControl
{
    public AvatarGroups() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class AvatarSizes : UserControl
{
    public AvatarSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BadgeColors : UserControl
{
    public BadgeColors() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BadgeCount : UserControl
{
    public BadgeCount() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BadgeDemo : UserControl
{
    public BadgeDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BadgeSizes : UserControl
{
    public BadgeSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BreadcrumbDemo : UserControl
{
    public BreadcrumbDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BreadcrumbDisabled : UserControl
{
    public BreadcrumbDisabled() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BubbleDemo : UserControl
{
    public BubbleDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BubbleReaction : UserControl
{
    public BubbleReaction() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class BubbleVariants : UserControl
{
    public BubbleVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonGroupDemo : UserControl
{
    public ButtonGroupDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonGroupSizes : UserControl
{
    public ButtonGroupSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonGroupVariants : UserControl
{
    public ButtonGroupVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonGroupVertical : UserControl
{
    public ButtonGroupVertical() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonCompact : UserControl
{
    public ButtonCompact() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonDemo : UserControl
{
    public ButtonDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonDisabled : UserControl
{
    public ButtonDisabled() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonIcons : UserControl
{
    public ButtonIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonOutline : UserControl
{
    public ButtonOutline() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonRounded : UserControl
{
    public ButtonRounded() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonSizes : UserControl
{
    public ButtonSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ButtonVariants : UserControl
{
    public ButtonVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CalendarDemo : UserControl
{
    public CalendarDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CalendarFirstDay : UserControl
{
    public CalendarFirstDay() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CalendarSizes : UserControl
{
    public CalendarSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CalendarYear : UserControl
{
    public CalendarYear() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CarouselDemo : UserControl
{
    public CarouselDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CarouselSmall : UserControl
{
    public CarouselSmall() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CheckboxBare : UserControl
{
    public CheckboxBare() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CheckboxDemo : UserControl
{
    public CheckboxDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CheckboxIndeterminate : UserControl
{
    public CheckboxIndeterminate() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CheckboxSizes : UserControl
{
    public CheckboxSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ClipboardDemo : UserControl
{
    public ClipboardDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ClipboardSizes : UserControl
{
    public ClipboardSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CollapsibleDemo : UserControl
{
    public CollapsibleDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class CollapsibleUp : UserControl
{
    public CollapsibleUp() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ColorPickerDemo : UserControl
{
    public ColorPickerDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ColorPickerField : UserControl
{
    public ColorPickerField() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ColorPickerSizes : UserControl
{
    public ColorPickerSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ComboboxAutoComplete : UserControl
{
    public ComboboxAutoComplete() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ComboboxDemo : UserControl
{
    public ComboboxDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ComboboxFooter : UserControl
{
    public ComboboxFooter() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ComboboxMultiple : UserControl
{
    public ComboboxMultiple() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ComboboxSizes : UserControl
{
    public ComboboxSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ComboboxTrigger : UserControl
{
    public ComboboxTrigger() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DataTableDataGrid : UserControl
{
    public DataTableDataGrid() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DataTableDemo : UserControl
{
    public DataTableDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DataTableSizes : UserControl
{
    public DataTableSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DataTableStriped : UserControl
{
    public DataTableStriped() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DatePickerDemo : UserControl
{
    public DatePickerDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DatePickerSizes : UserControl
{
    public DatePickerSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DatePickerStates : UserControl
{
    public DatePickerStates() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DescriptionListBorderless : UserControl
{
    public DescriptionListBorderless() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DescriptionListDemo : UserControl
{
    public DescriptionListDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DescriptionListSizes : UserControl
{
    public DescriptionListSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DescriptionListVertical : UserControl
{
    public DescriptionListVertical() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DockDemo : UserControl
{
    public DockDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DockDocuments : UserControl
{
    public DockDocuments() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DockPinned : UserControl
{
    public DockPinned() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DropdownButtonDemo : UserControl
{
    public DropdownButtonDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DropdownButtonSizes : UserControl
{
    public DropdownButtonSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class DropdownButtonVariants : UserControl
{
    public DropdownButtonVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class EmptyDemo : UserControl
{
    public EmptyDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class EmptyVariants : UserControl
{
    public EmptyVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class FormColumns : UserControl
{
    public FormColumns() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class FormDemo : UserControl
{
    public FormDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class FormHorizontal : UserControl
{
    public FormHorizontal() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class FormSizes : UserControl
{
    public FormSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class GroupBoxDemo : UserControl
{
    public GroupBoxDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class GroupBoxVariants : UserControl
{
    public GroupBoxVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class HoverCardDemo : UserControl
{
    public HoverCardDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class HoverCardPlacements : UserControl
{
    public HoverCardPlacements() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class IconColors : UserControl
{
    public IconColors() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class IconDemo : UserControl
{
    public IconDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class IconSizes : UserControl
{
    public IconSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ImageDemo : UserControl
{
    public ImageDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ImageFit : UserControl
{
    public ImageFit() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ImageRounded : UserControl
{
    public ImageRounded() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputGroupAddons : UserControl
{
    public InputGroupAddons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputGroupButtons : UserControl
{
    public InputGroupButtons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputGroupDemo : UserControl
{
    public InputGroupDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputGroupStates : UserControl
{
    public InputGroupStates() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputDemo : UserControl
{
    public InputDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputIcons : UserControl
{
    public InputIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputPassword : UserControl
{
    public InputPassword() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputSizes : UserControl
{
    public InputSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class InputStates : UserControl
{
    public InputStates() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class KbdDemo : UserControl
{
    public KbdDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class KbdOutline : UserControl
{
    public KbdOutline() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class LabelDemo : UserControl
{
    public LabelDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class LabelSizes : UserControl
{
    public LabelSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class LabelStyles : UserControl
{
    public LabelStyles() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class LabelWrap : UserControl
{
    public LabelWrap() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class LinkDemo : UserControl
{
    public LinkDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class LinkInline : UserControl
{
    public LinkInline() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ListDemo : UserControl
{
    public ListDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ListEmpty : UserControl
{
    public ListEmpty() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ListLoading : UserControl
{
    public ListLoading() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ListSearch : UserControl
{
    public ListSearch() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ListSections : UserControl
{
    public ListSections() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MarkerAlignment : UserControl
{
    public MarkerAlignment() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MarkerDemo : UserControl
{
    public MarkerDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MarkerLoading : UserControl
{
    public MarkerLoading() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MenuContextMenu : UserControl
{
    public MenuContextMenu() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MenuDemo : UserControl
{
    public MenuDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MenuDropdown : UserControl
{
    public MenuDropdown() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MessageDemo : UserControl
{
    public MessageDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class MessagePlain : UserControl
{
    public MessagePlain() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class NotificationCard : UserControl
{
    public NotificationCard() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class NotificationDemo : UserControl
{
    public NotificationDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class NotificationTypes : UserControl
{
    public NotificationTypes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class NumberInputDemo : UserControl
{
    public NumberInputDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class NumberInputRange : UserControl
{
    public NumberInputRange() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class NumberInputSizes : UserControl
{
    public NumberInputSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class PaginationCompact : UserControl
{
    public PaginationCompact() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class PaginationDemo : UserControl
{
    public PaginationDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class PaginationSizes : UserControl
{
    public PaginationSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class PopoverDemo : UserControl
{
    public PopoverDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class PopoverPlacements : UserControl
{
    public PopoverPlacements() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class PopoverPlain : UserControl
{
    public PopoverPlain() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ProgressCircleDemo : UserControl
{
    public ProgressCircleDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ProgressCircleIndeterminate : UserControl
{
    public ProgressCircleIndeterminate() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ProgressCircleSizes : UserControl
{
    public ProgressCircleSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ProgressDemo : UserControl
{
    public ProgressDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ProgressIndeterminate : UserControl
{
    public ProgressIndeterminate() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ProgressSizes : UserControl
{
    public ProgressSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RadioDemo : UserControl
{
    public RadioDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RadioDisabled : UserControl
{
    public RadioDisabled() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RadioSizes : UserControl
{
    public RadioSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RatingColor : UserControl
{
    public RatingColor() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RatingDemo : UserControl
{
    public RatingDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RatingDisabled : UserControl
{
    public RatingDisabled() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RatingMaximum : UserControl
{
    public RatingMaximum() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class RatingSizes : UserControl
{
    public RatingSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ResizableDemo : UserControl
{
    public ResizableDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ResizableNested : UserControl
{
    public ResizableNested() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ResizableVertical : UserControl
{
    public ResizableVertical() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ScrollableDemo : UserControl
{
    public ScrollableDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ScrollableHorizontal : UserControl
{
    public ScrollableHorizontal() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ScrollableModes : UserControl
{
    public ScrollableModes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SelectClear : UserControl
{
    public SelectClear() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SelectDemo : UserControl
{
    public SelectDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SelectGroups : UserControl
{
    public SelectGroups() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SelectSearch : UserControl
{
    public SelectSearch() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SelectSizes : UserControl
{
    public SelectSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SelectStates : UserControl
{
    public SelectStates() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SeparatorDemo : UserControl
{
    public SeparatorDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SeparatorVariants : UserControl
{
    public SeparatorVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SheetDemo : UserControl
{
    public SheetDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SheetPlacements : UserControl
{
    public SheetPlacements() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ShimmerDemo : UserControl
{
    public ShimmerDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ShimmerVariants : UserControl
{
    public ShimmerVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SidebarDemo : UserControl
{
    public SidebarDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SidebarDrawer : UserControl
{
    public SidebarDrawer() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SidebarRight : UserControl
{
    public SidebarRight() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SkeletonDemo : UserControl
{
    public SkeletonDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SkeletonShapes : UserControl
{
    public SkeletonShapes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SliderDemo : UserControl
{
    public SliderDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SliderDisabled : UserControl
{
    public SliderDisabled() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SliderReverse : UserControl
{
    public SliderReverse() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SliderVertical : UserControl
{
    public SliderVertical() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SpinnerDemo : UserControl
{
    public SpinnerDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SpinnerInline : UserControl
{
    public SpinnerInline() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SpinnerSizes : UserControl
{
    public SpinnerSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class StatusBarDemo : UserControl
{
    public StatusBarDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class StatusBarRegions : UserControl
{
    public StatusBarRegions() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class StepperDemo : UserControl
{
    public StepperDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class StepperIcons : UserControl
{
    public StepperIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class StepperLayouts : UserControl
{
    public StepperLayouts() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class StepperSizes : UserControl
{
    public StepperSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SwitchDemo : UserControl
{
    public SwitchDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SwitchLabelLeft : UserControl
{
    public SwitchLabelLeft() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class SwitchSizes : UserControl
{
    public SwitchSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabaloniaDemo : UserControl
{
    public TabaloniaDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabaloniaPrefixSuffix : UserControl
{
    public TabaloniaPrefixSuffix() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabaloniaScrolling : UserControl
{
    public TabaloniaScrolling() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabaloniaSizes : UserControl
{
    public TabaloniaSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabaloniaVariants : UserControl
{
    public TabaloniaVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TableDemo : UserControl
{
    public TableDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TablePlain : UserControl
{
    public TablePlain() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TableSizes : UserControl
{
    public TableSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabsDemo : UserControl
{
    public TabsDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabsIcons : UserControl
{
    public TabsIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabsSizes : UserControl
{
    public TabsSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TabsVariants : UserControl
{
    public TabsVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TagColors : UserControl
{
    public TagColors() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TagDemo : UserControl
{
    public TagDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TagOutline : UserControl
{
    public TagOutline() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TagSizes : UserControl
{
    public TagSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TextareaAutoGrow : UserControl
{
    public TextareaAutoGrow() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TextareaDemo : UserControl
{
    public TextareaDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TextareaSizes : UserControl
{
    public TextareaSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TextareaStates : UserControl
{
    public TextareaStates() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TimeFieldDemo : UserControl
{
    public TimeFieldDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TimeFieldFormats : UserControl
{
    public TimeFieldFormats() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TimeFieldSizes : UserControl
{
    public TimeFieldSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TimeFieldStates : UserControl
{
    public TimeFieldStates() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TitleBarDemo : UserControl
{
    public TitleBarDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleGroupDemo : UserControl
{
    public ToggleGroupDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleGroupIcons : UserControl
{
    public ToggleGroupIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleGroupSizes : UserControl
{
    public ToggleGroupSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleGroupVariants : UserControl
{
    public ToggleGroupVariants() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleDemo : UserControl
{
    public ToggleDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleIcons : UserControl
{
    public ToggleIcons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleOutline : UserControl
{
    public ToggleOutline() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToggleSizes : UserControl
{
    public ToggleSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToolbarDemo : UserControl
{
    public ToolbarDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToolbarDisabled : UserControl
{
    public ToolbarDisabled() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class ToolbarSizes : UserControl
{
    public ToolbarSizes() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TooltipDemo : UserControl
{
    public TooltipDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TooltipIconButtons : UserControl
{
    public TooltipIconButtons() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TooltipPlacements : UserControl
{
    public TooltipPlacements() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TreeDemo : UserControl
{
    public TreeDemo() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TreeRounded : UserControl
{
    public TreeRounded() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TreeTreeItems : UserControl
{
    public TreeTreeItems() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class TreeVirtualized : UserControl
{
    public TreeVirtualized() => AvaloniaXamlLoader.Load(this);
}

public sealed partial class VirtualListDemo : UserControl
{
    public VirtualListDemo() => AvaloniaXamlLoader.Load(this);
}

public static partial class DemoRegistry
{
    /// <summary>Every demo by id (`&lt;component&gt;/&lt;name&gt;`), in id order.</summary>
    public static IReadOnlyDictionary<string, Func<Control>> Factories { get; } = new Dictionary<string, Func<Control>>
    {
        ["accordion/borderless"] = static () => new AccordionBorderless(),
        ["accordion/demo"] = static () => new AccordionDemo(),
        ["accordion/icons"] = static () => new AccordionIcons(),
        ["accordion/sizes"] = static () => new AccordionSizes(),
        ["alert/banner"] = static () => new AlertBanner(),
        ["alert/demo"] = static () => new AlertDemo(),
        ["alert/sizes"] = static () => new AlertSizes(),
        ["alert/variants"] = static () => new AlertVariants(),
        ["avatar/demo"] = static () => new AvatarDemo(),
        ["avatar/groups"] = static () => new AvatarGroups(),
        ["avatar/sizes"] = static () => new AvatarSizes(),
        ["badge/colors"] = static () => new BadgeColors(),
        ["badge/count"] = static () => new BadgeCount(),
        ["badge/demo"] = static () => new BadgeDemo(),
        ["badge/sizes"] = static () => new BadgeSizes(),
        ["breadcrumb/demo"] = static () => new BreadcrumbDemo(),
        ["breadcrumb/disabled"] = static () => new BreadcrumbDisabled(),
        ["bubble/demo"] = static () => new BubbleDemo(),
        ["bubble/reaction"] = static () => new BubbleReaction(),
        ["bubble/variants"] = static () => new BubbleVariants(),
        ["button-group/demo"] = static () => new ButtonGroupDemo(),
        ["button-group/sizes"] = static () => new ButtonGroupSizes(),
        ["button-group/variants"] = static () => new ButtonGroupVariants(),
        ["button-group/vertical"] = static () => new ButtonGroupVertical(),
        ["button/compact"] = static () => new ButtonCompact(),
        ["button/demo"] = static () => new ButtonDemo(),
        ["button/disabled"] = static () => new ButtonDisabled(),
        ["button/icons"] = static () => new ButtonIcons(),
        ["button/outline"] = static () => new ButtonOutline(),
        ["button/rounded"] = static () => new ButtonRounded(),
        ["button/sizes"] = static () => new ButtonSizes(),
        ["button/variants"] = static () => new ButtonVariants(),
        ["calendar/demo"] = static () => new CalendarDemo(),
        ["calendar/first-day"] = static () => new CalendarFirstDay(),
        ["calendar/sizes"] = static () => new CalendarSizes(),
        ["calendar/year"] = static () => new CalendarYear(),
        ["carousel/demo"] = static () => new CarouselDemo(),
        ["carousel/small"] = static () => new CarouselSmall(),
        ["checkbox/bare"] = static () => new CheckboxBare(),
        ["checkbox/demo"] = static () => new CheckboxDemo(),
        ["checkbox/indeterminate"] = static () => new CheckboxIndeterminate(),
        ["checkbox/sizes"] = static () => new CheckboxSizes(),
        ["clipboard/demo"] = static () => new ClipboardDemo(),
        ["clipboard/sizes"] = static () => new ClipboardSizes(),
        ["collapsible/demo"] = static () => new CollapsibleDemo(),
        ["collapsible/up"] = static () => new CollapsibleUp(),
        ["color-picker/demo"] = static () => new ColorPickerDemo(),
        ["color-picker/field"] = static () => new ColorPickerField(),
        ["color-picker/sizes"] = static () => new ColorPickerSizes(),
        ["combobox/auto-complete"] = static () => new ComboboxAutoComplete(),
        ["combobox/demo"] = static () => new ComboboxDemo(),
        ["combobox/footer"] = static () => new ComboboxFooter(),
        ["combobox/multiple"] = static () => new ComboboxMultiple(),
        ["combobox/sizes"] = static () => new ComboboxSizes(),
        ["combobox/trigger"] = static () => new ComboboxTrigger(),
        ["data-table/data-grid"] = static () => new DataTableDataGrid(),
        ["data-table/demo"] = static () => new DataTableDemo(),
        ["data-table/sizes"] = static () => new DataTableSizes(),
        ["data-table/striped"] = static () => new DataTableStriped(),
        ["date-picker/demo"] = static () => new DatePickerDemo(),
        ["date-picker/sizes"] = static () => new DatePickerSizes(),
        ["date-picker/states"] = static () => new DatePickerStates(),
        ["description-list/borderless"] = static () => new DescriptionListBorderless(),
        ["description-list/demo"] = static () => new DescriptionListDemo(),
        ["description-list/sizes"] = static () => new DescriptionListSizes(),
        ["description-list/vertical"] = static () => new DescriptionListVertical(),
        ["dock/demo"] = static () => new DockDemo(),
        ["dock/documents"] = static () => new DockDocuments(),
        ["dock/pinned"] = static () => new DockPinned(),
        ["dropdown-button/demo"] = static () => new DropdownButtonDemo(),
        ["dropdown-button/sizes"] = static () => new DropdownButtonSizes(),
        ["dropdown-button/variants"] = static () => new DropdownButtonVariants(),
        ["empty/demo"] = static () => new EmptyDemo(),
        ["empty/variants"] = static () => new EmptyVariants(),
        ["form/columns"] = static () => new FormColumns(),
        ["form/demo"] = static () => new FormDemo(),
        ["form/horizontal"] = static () => new FormHorizontal(),
        ["form/sizes"] = static () => new FormSizes(),
        ["group-box/demo"] = static () => new GroupBoxDemo(),
        ["group-box/variants"] = static () => new GroupBoxVariants(),
        ["hover-card/demo"] = static () => new HoverCardDemo(),
        ["hover-card/placements"] = static () => new HoverCardPlacements(),
        ["icon/colors"] = static () => new IconColors(),
        ["icon/demo"] = static () => new IconDemo(),
        ["icon/sizes"] = static () => new IconSizes(),
        ["image/demo"] = static () => new ImageDemo(),
        ["image/fit"] = static () => new ImageFit(),
        ["image/rounded"] = static () => new ImageRounded(),
        ["input-group/addons"] = static () => new InputGroupAddons(),
        ["input-group/buttons"] = static () => new InputGroupButtons(),
        ["input-group/demo"] = static () => new InputGroupDemo(),
        ["input-group/states"] = static () => new InputGroupStates(),
        ["input/demo"] = static () => new InputDemo(),
        ["input/icons"] = static () => new InputIcons(),
        ["input/password"] = static () => new InputPassword(),
        ["input/sizes"] = static () => new InputSizes(),
        ["input/states"] = static () => new InputStates(),
        ["kbd/demo"] = static () => new KbdDemo(),
        ["kbd/outline"] = static () => new KbdOutline(),
        ["label/demo"] = static () => new LabelDemo(),
        ["label/sizes"] = static () => new LabelSizes(),
        ["label/styles"] = static () => new LabelStyles(),
        ["label/wrap"] = static () => new LabelWrap(),
        ["link/demo"] = static () => new LinkDemo(),
        ["link/inline"] = static () => new LinkInline(),
        ["list/demo"] = static () => new ListDemo(),
        ["list/empty"] = static () => new ListEmpty(),
        ["list/loading"] = static () => new ListLoading(),
        ["list/search"] = static () => new ListSearch(),
        ["list/sections"] = static () => new ListSections(),
        ["marker/alignment"] = static () => new MarkerAlignment(),
        ["marker/demo"] = static () => new MarkerDemo(),
        ["marker/loading"] = static () => new MarkerLoading(),
        ["menu/context-menu"] = static () => new MenuContextMenu(),
        ["menu/demo"] = static () => new MenuDemo(),
        ["menu/dropdown"] = static () => new MenuDropdown(),
        ["message/demo"] = static () => new MessageDemo(),
        ["message/plain"] = static () => new MessagePlain(),
        ["notification/card"] = static () => new NotificationCard(),
        ["notification/demo"] = static () => new NotificationDemo(),
        ["notification/types"] = static () => new NotificationTypes(),
        ["number-input/demo"] = static () => new NumberInputDemo(),
        ["number-input/range"] = static () => new NumberInputRange(),
        ["number-input/sizes"] = static () => new NumberInputSizes(),
        ["pagination/compact"] = static () => new PaginationCompact(),
        ["pagination/demo"] = static () => new PaginationDemo(),
        ["pagination/sizes"] = static () => new PaginationSizes(),
        ["popover/demo"] = static () => new PopoverDemo(),
        ["popover/placements"] = static () => new PopoverPlacements(),
        ["popover/plain"] = static () => new PopoverPlain(),
        ["progress-circle/demo"] = static () => new ProgressCircleDemo(),
        ["progress-circle/indeterminate"] = static () => new ProgressCircleIndeterminate(),
        ["progress-circle/sizes"] = static () => new ProgressCircleSizes(),
        ["progress/demo"] = static () => new ProgressDemo(),
        ["progress/indeterminate"] = static () => new ProgressIndeterminate(),
        ["progress/sizes"] = static () => new ProgressSizes(),
        ["radio/demo"] = static () => new RadioDemo(),
        ["radio/disabled"] = static () => new RadioDisabled(),
        ["radio/sizes"] = static () => new RadioSizes(),
        ["rating/color"] = static () => new RatingColor(),
        ["rating/demo"] = static () => new RatingDemo(),
        ["rating/disabled"] = static () => new RatingDisabled(),
        ["rating/maximum"] = static () => new RatingMaximum(),
        ["rating/sizes"] = static () => new RatingSizes(),
        ["resizable/demo"] = static () => new ResizableDemo(),
        ["resizable/nested"] = static () => new ResizableNested(),
        ["resizable/vertical"] = static () => new ResizableVertical(),
        ["scrollable/demo"] = static () => new ScrollableDemo(),
        ["scrollable/horizontal"] = static () => new ScrollableHorizontal(),
        ["scrollable/modes"] = static () => new ScrollableModes(),
        ["select/clear"] = static () => new SelectClear(),
        ["select/demo"] = static () => new SelectDemo(),
        ["select/groups"] = static () => new SelectGroups(),
        ["select/search"] = static () => new SelectSearch(),
        ["select/sizes"] = static () => new SelectSizes(),
        ["select/states"] = static () => new SelectStates(),
        ["separator/demo"] = static () => new SeparatorDemo(),
        ["separator/variants"] = static () => new SeparatorVariants(),
        ["sheet/demo"] = static () => new SheetDemo(),
        ["sheet/placements"] = static () => new SheetPlacements(),
        ["shimmer/demo"] = static () => new ShimmerDemo(),
        ["shimmer/variants"] = static () => new ShimmerVariants(),
        ["sidebar/demo"] = static () => new SidebarDemo(),
        ["sidebar/drawer"] = static () => new SidebarDrawer(),
        ["sidebar/right"] = static () => new SidebarRight(),
        ["skeleton/demo"] = static () => new SkeletonDemo(),
        ["skeleton/shapes"] = static () => new SkeletonShapes(),
        ["slider/demo"] = static () => new SliderDemo(),
        ["slider/disabled"] = static () => new SliderDisabled(),
        ["slider/reverse"] = static () => new SliderReverse(),
        ["slider/vertical"] = static () => new SliderVertical(),
        ["spinner/demo"] = static () => new SpinnerDemo(),
        ["spinner/inline"] = static () => new SpinnerInline(),
        ["spinner/sizes"] = static () => new SpinnerSizes(),
        ["status-bar/demo"] = static () => new StatusBarDemo(),
        ["status-bar/regions"] = static () => new StatusBarRegions(),
        ["stepper/demo"] = static () => new StepperDemo(),
        ["stepper/icons"] = static () => new StepperIcons(),
        ["stepper/layouts"] = static () => new StepperLayouts(),
        ["stepper/sizes"] = static () => new StepperSizes(),
        ["switch/demo"] = static () => new SwitchDemo(),
        ["switch/label-left"] = static () => new SwitchLabelLeft(),
        ["switch/sizes"] = static () => new SwitchSizes(),
        ["tabalonia/demo"] = static () => new TabaloniaDemo(),
        ["tabalonia/prefix-suffix"] = static () => new TabaloniaPrefixSuffix(),
        ["tabalonia/scrolling"] = static () => new TabaloniaScrolling(),
        ["tabalonia/sizes"] = static () => new TabaloniaSizes(),
        ["tabalonia/variants"] = static () => new TabaloniaVariants(),
        ["table/demo"] = static () => new TableDemo(),
        ["table/plain"] = static () => new TablePlain(),
        ["table/sizes"] = static () => new TableSizes(),
        ["tabs/demo"] = static () => new TabsDemo(),
        ["tabs/icons"] = static () => new TabsIcons(),
        ["tabs/sizes"] = static () => new TabsSizes(),
        ["tabs/variants"] = static () => new TabsVariants(),
        ["tag/colors"] = static () => new TagColors(),
        ["tag/demo"] = static () => new TagDemo(),
        ["tag/outline"] = static () => new TagOutline(),
        ["tag/sizes"] = static () => new TagSizes(),
        ["textarea/auto-grow"] = static () => new TextareaAutoGrow(),
        ["textarea/demo"] = static () => new TextareaDemo(),
        ["textarea/sizes"] = static () => new TextareaSizes(),
        ["textarea/states"] = static () => new TextareaStates(),
        ["time-field/demo"] = static () => new TimeFieldDemo(),
        ["time-field/formats"] = static () => new TimeFieldFormats(),
        ["time-field/sizes"] = static () => new TimeFieldSizes(),
        ["time-field/states"] = static () => new TimeFieldStates(),
        ["title-bar/demo"] = static () => new TitleBarDemo(),
        ["toggle-group/demo"] = static () => new ToggleGroupDemo(),
        ["toggle-group/icons"] = static () => new ToggleGroupIcons(),
        ["toggle-group/sizes"] = static () => new ToggleGroupSizes(),
        ["toggle-group/variants"] = static () => new ToggleGroupVariants(),
        ["toggle/demo"] = static () => new ToggleDemo(),
        ["toggle/icons"] = static () => new ToggleIcons(),
        ["toggle/outline"] = static () => new ToggleOutline(),
        ["toggle/sizes"] = static () => new ToggleSizes(),
        ["toolbar/demo"] = static () => new ToolbarDemo(),
        ["toolbar/disabled"] = static () => new ToolbarDisabled(),
        ["toolbar/sizes"] = static () => new ToolbarSizes(),
        ["tooltip/demo"] = static () => new TooltipDemo(),
        ["tooltip/icon-buttons"] = static () => new TooltipIconButtons(),
        ["tooltip/placements"] = static () => new TooltipPlacements(),
        ["tree/demo"] = static () => new TreeDemo(),
        ["tree/rounded"] = static () => new TreeRounded(),
        ["tree/tree-items"] = static () => new TreeTreeItems(),
        ["tree/virtualized"] = static () => new TreeVirtualized(),
        ["virtual-list/demo"] = static () => new VirtualListDemo(),
    };
}
