// <auto-generated/>
// Generated by `bun sites/scripts/control-catalog.ts` from sites/app/lib/catalog.ts,
// sites/content/components/*.mdx and the site's code colors. Do not edit.
using AvaloniaUIKit.Demo.ControlCatalog.Code;

namespace AvaloniaUIKit.Demo.ControlCatalog;

public static partial class Catalog
{
    /// <summary>Every component, in the site's catalog order.</summary>
    public static IReadOnlyList<CatalogComponent> Components { get; } =
    [
        new(
            "accordion", "Accordion", "Accordion",
            CatalogSection.Avalonia, "Layout", ["Expander", "StackPanel.accordion"],
            null, null,
            "Expanders stacked in an accordion frame, opening and closing on a spring.",
            [
                new("accordion/demo", "Accordion/Demo", null, null, null),
                new("accordion/sizes", "Accordion/Sizes", "Sizes", "Examples", "The four sizes."),
                new("accordion/borderless", "Accordion/Borderless", "Borderless", "Examples", "Without the `Border` the items keep their separators but have no frame; the last item is disabled."),
                new("accordion/icons", "Accordion/Icons", "Icons", "Examples", "A header is any content: here an icon and a label in a horizontal `StackPanel`."),
            ]),
        new(
            "alert", "Alert", "Alert",
            CatalogSection.UIKit, "Feedback", ["uikit:Alert"],
            null, null,
            "A message with a title and an icon in the info, success, warning and error colors.",
            [
                new("alert/demo", "Alert/Demo", null, null, null),
                new("alert/variants", "Alert/Variants", "Variants", "Examples", "The default and the four variants, each with its icon."),
                new("alert/sizes", "Alert/Sizes", "Sizes", "Examples", "The four sizes, from 12 by 6 to 20 by 14 of padding; large takes the larger radius."),
                new("alert/banner", "Alert/Banner", "Banner", "Examples", "`banner` drops the corners and the title and centers the row; it combines with a variant, a size and `IsClosable`."),
            ]),
        new(
            "avatar", "Avatar", "Avatar, AvatarGroup",
            CatalogSection.UIKit, "Data display", ["uikit:Avatar", "uikit:AvatarGroup"],
            null, null,
            "A circular avatar with an image, initials or a placeholder, and a group that overlaps them.",
            [
                new("avatar/demo", "Avatar/Demo", null, null, null),
                new("avatar/sizes", "Avatar/Sizes", "Sizes", "Examples", "The four sizes with initials and with the placeholder."),
                new("avatar/groups", "Avatar/Groups", "Groups", "Examples", "A `small` group, a group of five cut to `Limit=\"3\"`, and the same with `ShowsEllipsis=\"True\"`."),
            ]),
        new(
            "badge", "Badge", "Badge",
            CatalogSection.UIKit, "Data display", ["uikit:Badge"],
            null, null,
            "A count, a dot or an icon over the top right corner of its content.",
            [
                new("badge/demo", "Badge/Demo", null, null, null),
                new("badge/count", "Badge/Count", "Count", "Examples", "Counts of 3, 12 and 100 (shown as 99+), and 12 with `Maximum=\"9\"`."),
                new("badge/sizes", "Badge/Sizes", "Sizes", "Examples", "`small` and `large` on the badge, with a count and with a dot; the dot stays 6px."),
                new("badge/colors", "Badge/Colors", "Colors", "Examples", "`BadgeBackground` takes any brush, such as the theme's palette colors."),
            ]),
        new(
            "breadcrumb", "Breadcrumb", "Breadcrumb",
            CatalogSection.UIKit, "Navigation", ["uikit:Breadcrumb", "uikit:BreadcrumbItem"],
            null, null,
            "Muted path items with a chevron between them; the last one in the foreground color.",
            [
                new("breadcrumb/demo", "Breadcrumb/Demo", null, null, null),
                new("breadcrumb/disabled", "Breadcrumb/Disabled", "Disabled", "Examples", "A disabled item (`IsEnabled=\"False\"`) stays muted and shows the arrow cursor instead of the hand."),
            ]),
        new(
            "bubble", "Bubble", "Bubble",
            CatalogSection.UIKit, "Data display", ["uikit:Bubble"],
            null, null,
            "A chat bubble: text on a rounded surface in one of seven looks, aligned to a side, with a reaction.",
            [
                new("bubble/demo", "Bubble/Demo", null, null, null),
                new("bubble/variants", "Bubble/Variants", "Variants", "Examples", "The seven looks."),
                new("bubble/reaction", "Bubble/Reaction", "Reactions", "Examples", "A reaction at its default place, with `reaction-start`, and with `reaction-top` on an `end` bubble."),
            ]),
        new(
            "button", "Button", "Button",
            CatalogSection.Avalonia, "Buttons", ["Button", "uikit:Buttons"],
            null, null,
            "A button in every color, modifier and size, as classes on Avalonia's Button.",
            [
                new("button/demo", "Button/Demo", null, null, null),
                new("button/variants", "Button/Variants", "Variants", "Examples", "Every color, including the paddingless `link` and `text` variants."),
                new("button/sizes", "Button/Sizes", "Sizes", "Examples", "The four sizes; medium needs no class."),
                new("button/outline", "Button/Outline", "Outline", "Examples", "`outline` gives each color its outlined look."),
                new("button/icons", "Button/Icons", "Icons", "Examples", "`icon-only` makes a square button (20, 24 or 32px by size) for a `PathIcon`, in any color; an icon beside a label is a horizontal `StackPanel` as the content."),
                new("button/compact", "Button/Compact", "Compact", "Examples", "`compact` narrows the padding and the minimum width at every size."),
                new("button/rounded", "Button/Rounded", "Rounded", "Examples", "The corner classes replace the theme radius, from square to a pill."),
                new("button/disabled", "Button/Disabled", "Disabled", "Examples", "`IsEnabled=\"False\"` switches every variant to its disabled colors."),
                new("button/loading", "Button/Loading", "Loading", "Examples", "`uikit:Buttons.IsLoading` on buttons with an icon, an icon alone and a label alone, and one with `LoadingIcon`; the last button loads for two seconds when clicked."),
                new("button/keep-focus", "Button/KeepFocus", "Keep focus", "Examples", "With `uikit:Buttons.TakesFocusOnPointer=\"False\"` on their panel, the buttons change the text selected in the `TextBox` without taking the focus from it."),
            ]),
        new(
            "button-group", "Button Group", "ButtonGroup",
            CatalogSection.Avalonia, "Buttons", ["StackPanel.button-group"],
            null, null,
            "Buttons joined into one bar, sharing their inner edges and keeping only the outer corners.",
            [
                new("button-group/demo", "ButtonGroup/Demo", null, null, null),
                new("button-group/variants", "ButtonGroup/Variants", "Variants", "Examples", "Default, primary and ghost groups, plain and outlined; the group takes any of the Button's colors."),
                new("button-group/sizes", "ButtonGroup/Sizes", "Sizes", "Examples", "The buttons' size classes set the group's size; give every button the same one."),
                new("button-group/vertical", "ButtonGroup/Vertical", "Vertical", "Examples", "`Orientation=\"Vertical\"` stacks the buttons and shares the horizontal edges instead."),
            ]),
        new(
            "calendar", "Calendar", "Calendar",
            CatalogSection.Avalonia, "Forms", ["Calendar"],
            null, null,
            "A month view in a bordered card, with month and year pickers.",
            [
                new("calendar/demo", "Calendar/Demo", null, null, null),
                new("calendar/sizes", "Calendar/Sizes", "Sizes", "Examples", "The small and large calendars."),
                new("calendar/year", "Calendar/Year", "Year view", "Examples", "The months grid, as `DisplayMode=\"Year\"` shows it."),
                new("calendar/first-day", "Calendar/FirstDay", "First day of week", "Examples", "`FirstDayOfWeek=\"Monday\"` reorders the weekday titles and the grid."),
            ]),
        new(
            "carousel", "Carousel", "Carousel",
            CatalogSection.Avalonia, "Layout", ["Carousel", "PipsPager.carousel", "uikit:CarouselPrevious", "uikit:CarouselNext"],
            null, null,
            "One page at a time, sliding on a spring, with dots as a PipsPager.",
            [
                new("carousel/demo", "Carousel/Demo", null, null, null),
                new("carousel/small", "Carousel/Small", "Small", "Examples", "A smaller carousel with `small` buttons and two pages."),
                new("carousel/drag", "Carousel/Drag", "Drag", "Pointer input", "Drag the pages, or use the buttons, the dots or the arrow keys."),
                new("carousel/loop", "Carousel/Loop", "Loop", "Pointer input", "`WrapSelection=\"True\"` with four pages and `small` buttons."),
                new("carousel/vertical", "Carousel/Vertical", "Vertical", "Pointer input", "A vertical carousel: its `PageTransition` is a vertical `uikit:SpringSlide`."),
            ]),
        new(
            "checkbox", "Checkbox", "Checkbox",
            CatalogSection.Avalonia, "Forms", ["CheckBox"],
            null, null,
            "A checkbox with the check mark fading in on a spring.",
            [
                new("checkbox/demo", "Checkbox/Demo", null, null, null),
                new("checkbox/sizes", "Checkbox/Sizes", "Sizes", "Examples", "The four sizes scale the box, the mark and the label."),
                new("checkbox/indeterminate", "Checkbox/Indeterminate", "Indeterminate", "Examples", "A three-state \"Select all\" box above the items it stands for. The states are static here; an app keeps them in sync through its bindings."),
                new("checkbox/bare", "Checkbox/Bare", "Bare", "Examples", "Label-less boxes for a table or list row; no class is needed."),
            ]),
        new(
            "clipboard", "Clipboard", "Clipboard",
            CatalogSection.UIKit, "Forms", ["uikit:Clipboard"],
            null, null,
            "A ghost icon button that copies its text and shows a check mark afterwards.",
            [
                new("clipboard/demo", "Clipboard/Demo", null, null, null),
                new("clipboard/sizes", "Clipboard/Sizes", "Sizes", "Examples", "The four sizes."),
            ]),
        new(
            "collapsible", "Collapsible", "Collapsible",
            CatalogSection.Avalonia, "Layout", ["Expander (UIKitCollapsible)"],
            null, null,
            "A header that reveals its content at its natural height, on a spring.",
            [
                new("collapsible/demo", "Collapsible/Demo", null, null, null),
                new("collapsible/up", "Collapsible/Up", "Expand up", "Examples", "`ExpandDirection=\"Up\"` reveals the content above the trigger."),
            ]),
        new(
            "color-picker", "Color Picker", "ColorPicker",
            CatalogSection.Avalonia, "Forms", ["ColorPicker"],
            "AvaloniaUIKit.ColorPicker", null,
            "Avalonia's ColorPicker as a swatch or an input field with a popover, from the AvaloniaUIKit.ColorPicker package.",
            [
                new("color-picker/demo", "ColorPicker/Demo", null, null, null),
                new("color-picker/sizes", "ColorPicker/Sizes", "Sizes", "Examples", "The four swatch sizes."),
                new("color-picker/field", "ColorPicker/Field", "Field", "Examples", "The `field` class in a column of 200px fields."),
            ]),
        new(
            "combobox", "Combobox", "Combobox",
            CatalogSection.Avalonia, "Forms", ["ComboBox.combobox", "AutoCompleteBox"],
            null, null,
            "A select that filters as you type, as ComboBox or AutoCompleteBox.",
            [
                new("combobox/demo", "Combobox/Demo", null, null, null),
                new("combobox/auto-complete", "Combobox/AutoComplete", "Auto-complete", "Examples", "An `AutoCompleteBox` filtering a list of fruit names. The demo takes its `ItemsSource` from a static helper that holds a list of strings; bind your own collection instead."),
                new("combobox/sizes", "Combobox/Sizes", "Sizes", "Examples", "A small and a medium combobox, and a disabled one."),
            ]),
        new(
            "data-table", "Data Table", "DataTable",
            CatalogSection.Avalonia, "Data display", ["TableView", "DataGrid"],
            "AvaloniaUIKit.DataGrid", null,
            "A data table as Avalonia's TableView, or DataGrid with the AvaloniaUIKit.DataGrid package.",
            [
                new("data-table/demo", "DataTable/Demo", null, null, null),
                new("data-table/striped", "DataTable/Striped", "Striped", "Examples", "`Classes=\"stripe\"` fills every other row and continues the stripes below the last row."),
                new("data-table/sizes", "DataTable/Sizes", "Sizes", "Examples", "`small` and `large` change the row height, the cell padding and (for `large`) the text size."),
                new("data-table/data-grid", "DataTable/DataGrid", "DataGrid", "Examples", "`DataGrid` with `UIKitDataGridTheme`: read-only, sortable from the headers, resizable columns, and an amount column right-aligned with `CellStyleClasses=\"text-right\"`."),
                new("data-table/cell-selection", "DataTable/CellSelection", "Cell selection", "Examples", "A `DataGrid` with `Classes=\"cell-selectable\"`: click a cell, then move with the arrow keys."),
                new("data-table/empty", "DataTable/Empty", "Empty", "Examples", "A table without rows."),
            ]),
        new(
            "date-picker", "Date Picker", "DatePicker",
            CatalogSection.Avalonia, "Forms", ["CalendarDatePicker"],
            null, null,
            "An input frame that opens a calendar.",
            [
                new("date-picker/demo", "DatePicker/Demo", null, null, null),
                new("date-picker/sizes", "DatePicker/Sizes", "Sizes", "Examples", "The four sizes."),
                new("date-picker/states", "DatePicker/States", "States", "Examples", "An empty field with its placeholder, a disabled field with a date, and a disabled empty one."),
            ]),
        new(
            "dock", "Dock", "Dock, DockArea, Panel, TabPanel",
            CatalogSection.ThirdParty, "Layout", ["DockControl"],
            "AvaloniaUIKit.Dock", "Dock.Avalonia",
            "Dock.Avalonia's docking layouts with a dock's tab bars, split handles and drop targets, from the AvaloniaUIKit.Dock package.",
            [
                new("dock/demo", "Dock/Demo", null, null, null),
                new("dock/documents", "Dock/Documents", "Documents", "Examples", "A document dock with close buttons and the create button."),
                new("dock/pinned", "Dock/Pinned", "Pinned tools", "Examples", "Tools pinned to the left edge; click one to show it."),
            ]),
        new(
            "description-list", "Description List", "DescriptionList",
            CatalogSection.UIKit, "Data display", ["uikit:DescriptionList"],
            null, null,
            "Labels and values in a grid, with spans and separators.",
            [
                new("description-list/demo", "DescriptionList/Demo", null, null, null),
                new("description-list/vertical", "DescriptionList/Vertical", "Vertical", "Examples", "`Orientation=\"Vertical\"` puts each label above its value."),
                new("description-list/borderless", "DescriptionList/Borderless", "Borderless", "Examples", "`IsBordered=\"False\"` for a plain grid without borders, fills or padding, in either orientation."),
                new("description-list/sizes", "DescriptionList/Sizes", "Sizes", "Examples", "The size classes change the padding; the large list here has two columns and 100px labels."),
            ]),
        new(
            "dropdown-button", "Dropdown Button", "DropdownButton",
            CatalogSection.Avalonia, "Buttons", ["SplitButton", "DropDownButton", "uikit:Buttons"],
            null, null,
            "A button with a caret half that opens a menu, as Avalonia's SplitButton; or a button with a caret, as DropDownButton.",
            [
                new("dropdown-button/demo", "DropdownButton/Demo", null, null, null),
                new("dropdown-button/variants", "DropdownButton/Variants", "Variants", "Examples", "The main colors, plain and outlined, and a disabled one. The demo keeps one `MenuFlyout` in the panel's resources and shares it through `Flyout=\"{StaticResource SaveMenu}\"`."),
                new("dropdown-button/sizes", "DropdownButton/Sizes", "Sizes", "Examples", "The four sizes scale both halves and the caret."),
                new("dropdown-button/caret", "DropdownButton/Caret", "DropDownButton", "Examples", "`DropDownButton` in a few colors, a small one and a disabled one, all opening the same menu."),
                new("dropdown-button/loading", "DropdownButton/Loading", "Loading", "Examples", "A loading action half; the caret half still opens the menu."),
            ]),
        new(
            "empty", "Empty", "Empty",
            CatalogSection.UIKit, "Feedback", ["uikit:EmptyState"],
            null, null,
            "An empty state: media, a title, a description and actions, centered.",
            [
                new("empty/demo", "Empty/Demo", null, null, null),
                new("empty/variants", "Empty/Variants", "Variants", "Examples", "A 40px icon as plain media, a bordered state with `icon-media`, a title alone, and content below the actions."),
            ]),
        new(
            "form", "Form", "Form, Field",
            CatalogSection.UIKit, "Forms", ["uikit:Form", "uikit:FormField"],
            null, null,
            "A form grid, with labelled fields, required marks and descriptions.",
            [
                new("form/demo", "Form/Demo", null, null, null),
                new("form/horizontal", "Form/Horizontal", "Horizontal labels", "Examples", "`LabelOrientation=\"Horizontal\"` puts the labels beside the inputs, 140px wide by default; `LabelWidth` narrows or widens them."),
                new("form/columns", "Form/Columns", "Columns", "Examples", "`Columns=\"2\"`, with the address field spanning both through `ColumnSpan=\"2\"`."),
                new("form/sizes", "Form/Sizes", "Sizes", "Examples", "`small` and `large` forms, with matching size classes on their inputs and footer buttons."),
            ]),
        new(
            "group-box", "Group Box", "GroupBox",
            CatalogSection.Avalonia, "Layout", ["GroupBox"],
            null, null,
            "A titled group in normal, fill and outline looks, as Avalonia's GroupBox.",
            [
                new("group-box/demo", "GroupBox/Demo", null, null, null),
                new("group-box/variants", "GroupBox/Variants", "Variants", "Examples", "Normal, fill and outline, and a fill group without a title."),
                new("group-box/footer", "GroupBox/Footer", "Footer", "Examples", "`uikit:GroupBoxes.Footer` adds supporting text under the surface: 14px muted text, 8px below it and aligned with the title."),
            ]),
        new(
            "hover-card", "Hover Card", "HoverCard",
            CatalogSection.UIKit, "Overlays", ["uikit:HoverCard"],
            null, null,
            "A card that opens next to its content on hover, after a delay, on the popover surface.",
            [
                new("hover-card/demo", "HoverCard/Demo", null, null, null),
                new("hover-card/placements", "HoverCard/Placements", "Placements", "Examples", "`Placement` on each card: top, bottom, aligned to the trigger's left edge, and right."),
            ]),
        new(
            "icon", "Icon", "Icon",
            CatalogSection.Avalonia, "Data display", ["PathIcon"],
            null, null,
            "Lucide icons as geometry for PathIcon.",
            [
                new("icon/demo", "Icon/Demo", null, null, null),
                new("icon/sizes", "Icon/Sizes", "Sizes", "Examples", "The three size classes, the default, and a 48px icon by `Width` and `Height`."),
                new("icon/colors", "Icon/Colors", "Colors", "Examples", "Color with `Foreground` (the theme's muted, primary and danger brushes here), and turn an icon with a `RenderTransform`."),
            ]),
        new(
            "image", "Image", "Image",
            CatalogSection.Avalonia, "Data display", ["Image"],
            null, null,
            "Avalonia's Image with rounded corners and five fits.",
            [
                new("image/demo", "Image/Demo", null, null, null),
                new("image/fit", "Image/Fit", "Object fit", "Examples", "The five fits in a 96px frame: a wide image for the first three, a small one for `DownOnly` and `None`."),
                new("image/rounded", "Image/Rounded", "Rounded", "Examples", "`rounded`, `rounded-lg` and `rounded-full` on a square image, and `rounded-full` on a wide one."),
            ]),
        new(
            "input", "Input", "Input",
            CatalogSection.Avalonia, "Forms", ["TextBox", "uikit:Inputs"],
            null, null,
            "An input frame with a focus ring and a placeholder, as Avalonia's TextBox.",
            [
                new("input/demo", "Input/Demo", null, null, null),
                new("input/sizes", "Input/Sizes", "Sizes", "Examples", "The four sizes."),
                new("input/icons", "Input/Icons", "Icons", "Examples", "A small search icon as `InnerLeftContent`, and an `xsmall` ghost icon button as `InnerRightContent`."),
                new("input/password", "Input/Password", "Password", "Examples", "A masked password, with and without the reveal button."),
                new("input/clear", "Input/Clear", "Clear button", "Examples", "The clear button, alone and after the reveal button."),
                new("input/states", "Input/States", "States", "Examples", "Read-only and disabled fields."),
                new("input/masks", "Input/Masks", "Masks", "Examples", "A phone number, a pattern of letters and digits, and an amount grouped by thousands with two decimals."),
                new("input/validation", "Input/Validation", "Validation", "Examples", "A field that takes letters and digits only, and one that Escape clears."),
            ]),
        new(
            "input-group", "Input Group", "InputGroup",
            CatalogSection.Avalonia, "Forms", ["TextBox.group"],
            null, null,
            "A text field with prefix and suffix addons inside one frame.",
            [
                new("input-group/demo", "InputGroup/Demo", null, null, null),
                new("input-group/addons", "InputGroup/Addons", "Addons", "Examples", "Text addons on both sides, and a read-only field with a suffix."),
                new("input-group/buttons", "InputGroup/Buttons", "Buttons", "Examples", "Buttons as the suffix: a text button, an `icon-only` one, and a multi-line group with a Send button."),
                new("input-group/states", "InputGroup/States", "States", "Examples", "An invalid group and a disabled one. The demo sets `DataValidationErrors.Errors` from a static helper that holds one validation message; an app gets its errors from its bindings' validation instead."),
            ]),
        new(
            "kbd", "Kbd", "Kbd",
            CatalogSection.UIKit, "Data display", ["uikit:Kbd"],
            null, null,
            "A key cap for keyboard shortcuts, written in each platform's notation.",
            [
                new("kbd/demo", "Kbd/Demo", null, null, null),
                new("kbd/outline", "Kbd/Outline", "Outline", "Examples", "`outline` on single keys and on a chord."),
            ]),
        new(
            "label", "Label", "Label",
            CatalogSection.Avalonia, "Data display", ["TextBlock.label", "Label"],
            null, null,
            "A fixed line height and secondary text, for TextBlock and Label.",
            [
                new("label/demo", "Label/Demo", null, null, null),
                new("label/sizes", "Label/Sizes", "Sizes", "Examples", "Font sizes from 12 to 24 on the same 20px line; text taller than the line overflows it, centered and unclipped."),
                new("label/styles", "Label/Styles", "Styles", "Examples", "Weights with a secondary run, colors with `Foreground`, and `TextAlignment` in a fixed width."),
                new("label/wrap", "Label/Wrap", "Wrap", "Examples", "A label wraps when its width is constrained; `LineHeight` replaces the 20px line."),
            ]),
        new(
            "link", "Link", "Link",
            CatalogSection.Avalonia, "Buttons", ["HyperlinkButton"],
            null, null,
            "A text link in the link color, as HyperlinkButton.",
            [
                new("link/demo", "Link/Demo", null, null, null),
                new("link/inline", "Link/Inline", "Inline", "Examples", "Links between `TextBlock`s in a horizontal `StackPanel`, centred vertically so they read as one sentence."),
            ]),
        new(
            "list", "List", "List",
            CatalogSection.Avalonia, "Data display", ["ListBox"],
            null, null,
            "List rows with hover, selection and the overlay scrollbar, as ListBox.",
            [
                new("list/demo", "List/Demo", null, null, null),
                new("list/empty", "List/Empty", "Empty", "Examples", "An empty list shows a 48px Inbox icon, centered; there is nothing to add for it."),
            ]),
        new(
            "marker", "Marker", "Marker",
            CatalogSection.UIKit, "Feedback", ["uikit:Marker"],
            null, null,
            "A muted status line with an icon or a spinner, and optional separators.",
            [
                new("marker/demo", "Marker/Demo", null, null, null),
                new("marker/alignment", "Marker/Alignment", "Alignment", "Examples", "`HorizontalContentAlignment` places the content and its separators at the start, center or end; without separators the row itself moves."),
                new("marker/loading", "Marker/Loading", "Loading", "Examples", "`IsLoading` leads with a spinner, or shimmers the text with `shimmer`; separators stay."),
            ]),
        new(
            "menu", "Menu", "Menu, ContextMenu, DropdownMenu, AppMenuBar",
            CatalogSection.Avalonia, "Overlays", ["Menu", "ContextMenu", "MenuFlyout"],
            null, null,
            "Popup menus and a menu bar: Menu, ContextMenu and MenuFlyout.",
            [
                new("menu/demo", "Menu/Demo", null, null, null),
                new("menu/context-menu", "Menu/ContextMenu", "Context menu", "Examples", "A `ContextMenu` on a control: an icon, a shortcut, a check item, a separator, a disabled item and a submenu."),
                new("menu/dropdown", "Menu/Dropdown", "Dropdown", "Examples", "A dropdown menu: a `Button` with a `MenuFlyout`, placed below its left edge."),
            ]),
        new(
            "message", "Message", "Message",
            CatalogSection.UIKit, "Data display", ["uikit:Message"],
            null, null,
            "A chat message: bubbles with a header, a footer and an avatar, aligned to a side.",
            [
                new("message/demo", "Message/Demo", null, null, null),
                new("message/plain", "Message/Plain", "Plain", "Examples", "Without bubbles: the items are strings, shown as plain text under the header."),
            ]),
        new(
            "notification", "Notification", "Notification",
            CatalogSection.Avalonia, "Feedback", ["WindowNotificationManager", "NotificationCard"],
            null, null,
            "Notification cards, sliding in and fading out, as Avalonia's WindowNotificationManager.",
            [
                new("notification/demo", "Notification/Demo", null, null, null),
                new("notification/types", "Notification/Types", "Types", "Examples", "The four types and the plain card; each button's `Click` handler creates the manager for the top level once and calls `Show` with the type from its `Tag`."),
                new("notification/card", "Notification/Card", "Card", "Examples", "A mock of the card's look, drawn with the theme's tokens so that it can sit on the page; real cards come from `WindowNotificationManager` and slide in."),
            ]),
        new(
            "number-input", "Number Input", "NumberInput",
            CatalogSection.Avalonia, "Forms", ["NumericUpDown"],
            null, null,
            "A numeric field with minus and plus buttons, as NumericUpDown.",
            [
                new("number-input/demo", "NumberInput/Demo", null, null, null),
                new("number-input/sizes", "NumberInput/Sizes", "Sizes", "Examples", "The four sizes."),
                new("number-input/range", "NumberInput/Range", "Range and format", "Examples", "A range of 0 to 100 in steps of 10, a decimal field with `Increment=\"0.5\"` and `FormatString=\"0.0\"`, and a disabled one."),
                new("number-input/affixes", "NumberInput/Affixes", "Prefix and suffix", "Examples", "A currency sign as `InnerLeftContent`, a unit as `InnerRightContent`, and an icon."),
            ]),
        new(
            "pagination", "Pagination", "Pagination",
            CatalogSection.Avalonia, "Navigation", ["PipsPager"],
            null, null,
            "Previous, numbered pages and Next, as a PipsPager.",
            [
                new("pagination/demo", "Pagination/Demo", null, null, null),
                new("pagination/sizes", "Pagination/Sizes", "Sizes", "Examples", "The four sizes."),
                new("pagination/compact", "Pagination/Compact", "Compact", "Examples", "`compact` with `small`, at the default size, and disabled."),
            ]),
        new(
            "popover", "Popover", "Popover",
            CatalogSection.Avalonia, "Overlays", ["Flyout"],
            null, null,
            "The popover surface, with an arrow or without any surface, as Avalonia's Flyout.",
            [
                new("popover/demo", "Popover/Demo", null, null, null),
                new("popover/placements", "Popover/Placements", "Placements", "Examples", "The eight placements; each slides to stay on screen instead of flipping."),
                new("popover/plain", "Popover/Plain", "Plain", "Examples", "`plain` draws the content alone; here an `Alert` brings its own surface."),
            ]),
        new(
            "progress", "Progress", "Progress",
            CatalogSection.Avalonia, "Feedback", ["ProgressBar"],
            null, null,
            "A progress bar, determinate and indeterminate, as Avalonia's ProgressBar.",
            [
                new("progress/demo", "Progress/Demo", null, null, null),
                new("progress/sizes", "Progress/Sizes", "Sizes", "Examples", "The four heights."),
                new("progress/indeterminate", "Progress/Indeterminate", "Indeterminate", "Examples", "`IsIndeterminate=\"True\"` repeats the sweep."),
            ]),
        new(
            "progress-circle", "Progress Circle", "ProgressCircle",
            CatalogSection.Avalonia, "Feedback", ["ProgressBar (UIKitProgressCircle)"],
            null, null,
            "A ring showing progress, as a ProgressBar with a named theme.",
            [
                new("progress-circle/demo", "ProgressCircle/Demo", null, null, null),
                new("progress-circle/sizes", "ProgressCircle/Sizes", "Sizes", "Examples", "The four sizes and an 80px ring, whose stroke stops at 5px."),
                new("progress-circle/indeterminate", "ProgressCircle/Indeterminate", "Indeterminate", "Examples", "The indeterminate arc at medium, large and 40px."),
                new("progress-circle/content", "ProgressCircle/Content", "Content", "Examples", "`uikit:ProgressCircles.Content` puts content in the middle of the ring, in the text color: here the value as a percentage in an 80px ring."),
            ]),
        new(
            "radio", "Radio", "Radio",
            CatalogSection.Avalonia, "Forms", ["RadioButton"],
            null, null,
            "A radio button, with the dot fading in on a spring.",
            [
                new("radio/demo", "Radio/Demo", null, null, null),
                new("radio/sizes", "Radio/Sizes", "Sizes", "Examples", "The four sizes; each is in its own group here so that all four can be checked."),
                new("radio/disabled", "Radio/Disabled", "Disabled", "Examples", "`IsEnabled=\"False\"` fades the circle, the dot and the label."),
            ]),
        new(
            "rating", "Rating", "Rating",
            CatalogSection.UIKit, "Forms", ["uikit:Rating"],
            null, null,
            "Stars to pick and show a rating.",
            [
                new("rating/demo", "Rating/Demo", null, null, null),
                new("rating/sizes", "Rating/Sizes", "Sizes", "Examples", "The four sizes."),
                new("rating/maximum", "Rating/Maximum", "Maximum", "Examples", "`Maximum` sets the number of stars."),
                new("rating/color", "Rating/Color", "Color", "Examples", "`ActiveBrush` colors the filled and previewed stars; the theme's `UIKit.Red` and `UIKit.Primary` here."),
                new("rating/disabled", "Rating/Disabled", "Disabled", "Examples", "A disabled rating neither previews nor changes."),
            ]),
        new(
            "resizable", "Resizable", "Resizable",
            CatalogSection.Avalonia, "Layout", ["GridSplitter"],
            null, null,
            "A resize handle between panels, as Avalonia's GridSplitter.",
            [
                new("resizable/demo", "Resizable/Demo", null, null, null),
                new("resizable/vertical", "Resizable/Vertical", "Vertical", "Examples", "`ResizeDirection=\"Rows\"` in a 1px row."),
                new("resizable/nested", "Resizable/Nested", "Nested", "Examples", "A splitter in each direction, the second grid nested in the first's column."),
            ]),
        new(
            "scrollable", "Scrollable", "Scrollable, Scrollbar",
            CatalogSection.Avalonia, "Layout", ["ScrollViewer"],
            null, null,
            "Overlay scrollbars, as Avalonia's ScrollViewer.",
            [
                new("scrollable/demo", "Scrollable/Demo", null, null, null),
                new("scrollable/modes", "Scrollable/Modes", "Modes", "Examples", "The three modes side by side."),
                new("scrollable/horizontal", "Scrollable/Horizontal", "Horizontal", "Examples", "A horizontal scrollbar, with `HorizontalScrollBarVisibility=\"Auto\"`."),
            ]),
        new(
            "select", "Select", "Select",
            CatalogSection.Avalonia, "Forms", ["ComboBox"],
            null, null,
            "A select: an input frame that opens a list in its popover.",
            [
                new("select/demo", "Select/Demo", null, null, null),
                new("select/sizes", "Select/Sizes", "Sizes", "Examples", "The four sizes."),
                new("select/states", "Select/States", "States", "Examples", "A disabled item in the list, a disabled select with a value, and a disabled one showing its placeholder."),
                new("select/clearable", "Select/Clearable", "Clear button", "Examples", "The clear button, with a value and without one."),
                new("select/editable", "Select/Editable", "Editable", "Examples", "An editable select: type a fruit's name or pick it from the list."),
            ]),
        new(
            "separator", "Separator", "Separator",
            CatalogSection.Avalonia, "Layout", ["Separator"],
            null, null,
            "A 1px line in the border color, horizontal, vertical or dashed.",
            [
                new("separator/demo", "Separator/Demo", null, null, null),
                new("separator/variants", "Separator/Variants", "Variants", "Examples", "Solid and dashed, horizontal and vertical."),
                new("separator/label", "Separator/Label", "Label", "Examples", "`uikit:Separators.Label` puts 12px muted text on the line, over the page background: at the end of a horizontal line and in the middle of a vertical one. A labeled separator is as tall (or, vertical, as wide) as its label."),
            ]),
        new(
            "settings", "Settings", "Settings, SettingPage, SettingGroup, SettingItem, Preferences",
            CatalogSection.UIKit, "Layout", ["uikit:Settings", "uikit:SettingPage", "uikit:SettingGroup", "uikit:SettingItem"],
            null, null,
            "A settings window with searchable pages, grouped items and a reset button, as uikit:Settings.",
            [
                new("settings/demo", "Settings/Demo", null, null, null),
                new("settings/items", "Settings/Items", "Items", "Examples", "The fields are the standard controls, in a group used on its own."),
                new("settings/group-variants", "Settings/GroupVariants", "Group variants", "Examples", "`Variant` on a group, or `GroupVariant` on the settings for every group: the items on the page, on a filled surface, or in a bordered card."),
                new("settings/reset", "Settings/Reset", "Reset", "Examples", "With a `DefaultValue`, an item follows a `ToggleSwitch` or `CheckBox` (`IsChecked`), a `TextBox` (`Text`), a `NumericUpDown` or `Slider` (`Value`), a `ComboBox` or `ListBox` (`SelectedValue`) and a `uikit:Select` (`SelectedItem`); a default written in XAML is text converted to the field's type. While a field differs from its default, the page shows a reset button that sets every item the search keeps back to its default, through the field's bindings. Other content sets `IsModified` itself and puts its default back in `Reset` or `ResetCommand`."),
            ]),
        new(
            "sheet", "Sheet", "Sheet",
            CatalogSection.Avalonia, "Overlays", ["DrawerPage.sheet"],
            null, null,
            "A panel sliding in from a side over the dimmed content, as DrawerPage in its overlay mode.",
            [
                new("sheet/demo", "Sheet/Demo", null, null, null),
                new("sheet/placements", "Sheet/Placements", "Placements", "Examples", "The four sides at 240px; each button's `Click` handler sets `DrawerPlacement` from its `Tag` and opens the sheet."),
            ]),
        new(
            "shimmer", "Shimmer", "Shimmer",
            CatalogSection.UIKit, "Feedback", ["uikit:ShimmerText"],
            null, null,
            "Text with a highlight sweeping across it.",
            [
                new("shimmer/demo", "Shimmer/Demo", null, null, null),
                new("shimmer/variants", "Shimmer/Variants", "Variants", "Examples", "The default sweep, a muted text, a reversed sweep, a 14px text, and a faster and wider band."),
            ]),
        new(
            "sidebar", "Sidebar", "Sidebar",
            CatalogSection.Avalonia, "Navigation", ["SplitView", "DrawerPage"],
            null, null,
            "A sidebar collapsing to icons or off canvas, as SplitView and DrawerPage.",
            [
                new("sidebar/demo", "Sidebar/Demo", null, null, null),
                new("sidebar/right", "Sidebar/Right", "Right", "Examples", "`PanePlacement=\"Right\"` for a pane on the right; the border stays on the content side."),
                new("sidebar/drawer", "Sidebar/Drawer", "DrawerPage", "Examples", "`DrawerPage` in `CompactInline`: the header holds the title and the toggle, the footer an avatar."),
            ]),
        new(
            "skeleton", "Skeleton", "Skeleton",
            CatalogSection.UIKit, "Feedback", ["uikit:Skeleton"],
            null, null,
            "A placeholder bar pulsing while content loads.",
            [
                new("skeleton/demo", "Skeleton/Demo", null, null, null),
                new("skeleton/shapes", "Skeleton/Shapes", "Shapes", "Examples", "A line, a secondary line, a rounded block, a circle and a card."),
            ]),
        new(
            "slider", "Slider", "Slider",
            CatalogSection.Avalonia, "Forms", ["Slider"],
            null, null,
            "A pill track filled up to the value, with a ring around the thumb on hover and drag.",
            [
                new("slider/demo", "Slider/Demo", null, null, null),
                new("slider/vertical", "Slider/Vertical", "Vertical", "Examples", "Vertical sliders at the minimum, a value and the maximum."),
                new("slider/reverse", "Slider/Reverse", "Reverse", "Examples", "A normal and a `reverse` slider at the same value."),
                new("slider/disabled", "Slider/Disabled", "Disabled", "Examples", "Disabled sliders keep their fill but draw no thumb."),
            ]),
        new(
            "spinner", "Spinner", "Spinner",
            CatalogSection.Avalonia, "Feedback", ["ProgressBar (UIKitSpinner)"],
            null, null,
            "A turning loader icon, as a ProgressBar with a named theme.",
            [
                new("spinner/demo", "Spinner/Demo", null, null, null),
                new("spinner/sizes", "Spinner/Sizes", "Sizes", "Examples", "The four sizes."),
                new("spinner/inline", "Spinner/Inline", "Inline", "Examples", "A spinner beside text, one in the muted color, and one inside a disabled button in the button's foreground."),
                new("spinner/icon", "Spinner/Icon", "Icon", "Examples", "`uikit:Spinners.Icon` replaces the loader with another icon geometry, here `UIKit.Icon.LoaderCircle`, plain and in cyan."),
            ]),
        new(
            "status-bar", "Status Bar", "StatusBar",
            CatalogSection.UIKit, "Data display", ["uikit:StatusBar"],
            null, null,
            "A thin bar of muted regions along the bottom of a window.",
            [
                new("status-bar/demo", "StatusBar/Demo", null, null, null),
                new("status-bar/regions", "StatusBar/Regions", "Regions", "Examples", "A bar with `Left` and content, one with content and `Right`, and one with content alone: with `Left` set the content moves to the end, otherwise it stays at the start."),
            ]),
        new(
            "stepper", "Stepper", "Stepper",
            CatalogSection.UIKit, "Navigation", ["uikit:Stepper"],
            null, null,
            "Numbered or icon steps joined by lines, with the current one highlighted.",
            [
                new("stepper/demo", "Stepper/Demo", null, null, null),
                new("stepper/icons", "Stepper/Icons", "Icons", "Examples", "`Icon` on an item replaces its number."),
                new("stepper/sizes", "Stepper/Sizes", "Sizes", "Examples", "The four sizes."),
                new("stepper/layouts", "Stepper/Layouts", "Layouts", "Examples", "`CentersSteps=\"True\"`, and `Orientation=\"Vertical\"`."),
            ]),
        new(
            "switch", "Switch", "Switch",
            CatalogSection.Avalonia, "Forms", ["ToggleSwitch"],
            null, null,
            "An on-off switch, with the thumb sliding on a spring.",
            [
                new("switch/demo", "Switch/Demo", null, null, null),
                new("switch/sizes", "Switch/Sizes", "Sizes", "Examples", "The four sizes."),
                new("switch/label-left", "Switch/LabelLeft", "Label left", "Examples", "`label-left` for a settings row where the label leads."),
            ]),
        new(
            "table", "Table", "Table",
            CatalogSection.Avalonia, "Data display", ["TableView (UIKitTable)"],
            null, null,
            "A plain table, as a TableView with a named theme.",
            [
                new("table/demo", "Table/Demo", null, null, null),
                new("table/plain", "Table/Plain", "Plain", "Examples", "The default look: no border, no stripes, and the first and last columns fixed at 100px."),
                new("table/sizes", "Table/Sizes", "Sizes", "Examples", "The size classes change only the padding of the cells."),
            ]),
        new(
            "tabs", "Tabs", "Tabs, TabBar, closable tabs, draggable tabs",
            CatalogSection.Avalonia, "Navigation", ["TabStrip", "TabControl", "uikit:Tabs"],
            null, null,
            "A tab bar in its default, outline, pill, segmented and underline looks, as TabStrip and TabControl.",
            [
                new("tabs/demo", "Tabs/Demo", null, null, null),
                new("tabs/variants", "Tabs/Variants", "Variants", "Examples", "The five looks; the last underline tab is disabled."),
                new("tabs/sizes", "Tabs/Sizes", "Sizes", "Examples", "The four sizes of a pill strip."),
                new("tabs/icons", "Tabs/Icons", "Icon only", "Examples", "`icon-only` items in a pill and in a segmented strip."),
                new("tabs/menu", "Tabs/Menu", "Menu", "Menu, prefix and suffix", "Six tabs in a 400px bar with a menu, a prefix and a suffix."),
                new("tabs/closable", "Tabs/Closable", "Closable", "Closing, adding and dragging", "A closable tab bar whose add button opens new tabs, and whose tabs can be reordered. The last tab cannot be closed."),
                new("tabs/reorder", "Tabs/Reorder", "Reorder", "Closing, adding and dragging", "Tabs reordered by dragging."),
                new("tabs/drag-group", "Tabs/DragGroup", "Drag group", "Closing, adding and dragging", "Two bars of one group: drag a tab from one to the other."),
            ]),
        new(
            "tag", "Tag", "Tag",
            CatalogSection.UIKit, "Data display", ["uikit:TagLabel"],
            null, null,
            "A small colored label, filled or outlined, in the theme's and the palette's colors.",
            [
                new("tag/demo", "Tag/Demo", null, null, null),
                new("tag/outline", "Tag/Outline", "Outline", "Examples", "`outline` with each theme color."),
                new("tag/sizes", "Tag/Sizes", "Sizes", "Examples", "The sizes, and `rounded-full` on a small and on a medium tag."),
                new("tag/colors", "Tag/Colors", "Colors", "Examples", "The nineteen palette colors, filled and with `outline`."),
            ]),
        new(
            "textarea", "Textarea", "Textarea",
            CatalogSection.Avalonia, "Forms", ["TextBox (AcceptsReturn)", "uikit:Inputs"],
            null, null,
            "A multi-line input in the Input's frame, as TextBox with AcceptsReturn.",
            [
                new("textarea/demo", "Textarea/Demo", null, null, null),
                new("textarea/auto-grow", "Textarea/AutoGrow", "Auto grow", "Examples", "`MinLines=\"2\" MaxLines=\"5\"`: the field grows with its text from two to five lines, then scrolls."),
                new("textarea/sizes", "Textarea/Sizes", "Sizes", "Examples", "The four sizes, each two lines tall."),
                new("textarea/states", "Textarea/States", "States", "Examples", "Read-only and disabled textareas."),
                new("textarea/indent", "Textarea/Indent", "Indent", "Examples", "Select lines and press Tab or Shift+Tab."),
            ]),
        new(
            "time-field", "Time Field", "TimeField",
            CatalogSection.Avalonia, "Forms", ["TimePicker"],
            null, null,
            "Hour and minute segments in an input frame, as TimePicker.",
            [
                new("time-field/demo", "TimeField/Demo", null, null, null),
                new("time-field/sizes", "TimeField/Sizes", "Sizes", "Examples", "The four sizes."),
                new("time-field/formats", "TimeField/Formats", "Formats", "Examples", "24-hour and 12-hour clocks, with and without seconds."),
                new("time-field/states", "TimeField/States", "States", "Examples", "A disabled field and an invalid one. The demo sets `DataValidationErrors.Errors` from a static helper that holds one validation message; an app gets its errors from its bindings' validation instead."),
            ]),
        new(
            "title-bar", "Title Bar", "TitleBar",
            CatalogSection.Avalonia, "Layout", ["WindowDrawnDecorations"],
            null, null,
            "A title bar and window border, as the decorations Avalonia draws itself.",
            [
                new("title-bar/demo", "TitleBar/Demo", null, null, "The demo is a mock: `WindowDrawnDecorations` only renders inside a real window, so the page builds the same bar from the theme's pieces (the gradient, the rule, `UIKitCaptionButton` with its `close` class, and the `UIKit.TitleBar.*` resources). In an app nothing is composed by hand: the theme applies to the window chrome itself."),
            ]),
        new(
            "toggle", "Toggle", "Toggle",
            CatalogSection.Avalonia, "Buttons", ["ToggleButton"],
            null, null,
            "A toggle button, ghost or outlined, as ToggleButton.",
            [
                new("toggle/demo", "Toggle/Demo", null, null, null),
                new("toggle/outline", "Toggle/Outline", "Outline", "Examples", "The outlined variant, checked, unchecked and disabled."),
                new("toggle/sizes", "Toggle/Sizes", "Sizes", "Examples", "The four sizes."),
                new("toggle/icons", "Toggle/Icons", "Icons", "Examples", "A `PathIcon` as the content makes a square toggle, ghost or outlined."),
            ]),
        new(
            "toggle-group", "Toggle Group", "ToggleGroup",
            CatalogSection.Avalonia, "Buttons", ["ListBox.toggle-group"],
            null, null,
            "Toggles that select one or several items, as a ListBox with the toggle-group class.",
            [
                new("toggle-group/demo", "ToggleGroup/Demo", null, null, null),
                new("toggle-group/variants", "ToggleGroup/Variants", "Variants", "Examples", "Ghost and outlined, loose and `segmented`. The segmented groups use `SelectionMode=\"Toggle\"`, so one item is selected at a time and clicking it again clears the selection."),
                new("toggle-group/sizes", "ToggleGroup/Sizes", "Sizes", "Examples", "The four sizes of an outlined group."),
                new("toggle-group/icons", "ToggleGroup/Icons", "Icons", "Examples", "A `PathIcon` as an item's content; the icon follows the group's size."),
            ]),
        new(
            "toolbar", "Toolbar", "Toolbar",
            CatalogSection.Avalonia, "Navigation", ["CommandBar"],
            null, null,
            "A toolbar of ghost buttons and separators, as CommandBar.",
            [
                new("toolbar/demo", "Toolbar/Demo", null, null, null),
                new("toolbar/sizes", "Toolbar/Sizes", "Sizes", "Examples", "`xsmall`, the default, and `medium`."),
                new("toolbar/disabled", "Toolbar/Disabled", "Disabled", "Examples", "`IsEnabled=\"False\"` on the bar disables every command."),
            ]),
        new(
            "tooltip", "Tooltip", "Tooltip",
            CatalogSection.Avalonia, "Overlays", ["ToolTip"],
            null, null,
            "A tooltip bubble, fading and sliding in above its trigger, as ToolTip.",
            [
                new("tooltip/demo", "Tooltip/Demo", null, null, null),
                new("tooltip/placements", "Tooltip/Placements", "Placements", "Examples", "`ToolTip.Placement` on each button: the default top, then bottom, left and right."),
                new("tooltip/icon-buttons", "Tooltip/IconButtons", "Icon buttons", "Examples", "A tooltip as the label of `icon-only` buttons."),
            ]),
        new(
            "tree", "Tree", "Tree",
            CatalogSection.Avalonia, "Data display", ["TreeView"],
            null, null,
            "Tree rows with folder and file icons, as TreeView.",
            [
                new("tree/demo", "Tree/Demo", null, null, null),
                new("tree/rounded", "Tree/Rounded", "Rounded", "Examples", "For a framed tree, give the `TreeView` a border, `Padding` and `CornerRadius`, and round the rows with a `Style` that sets `CornerRadius` on `TreeViewItem`."),
            ]),
        new(
            "uikit-accordion", "Accordion", "Accordion",
            CatalogSection.UIKit, "Layout", ["uikit:Accordion"],
            null, null,
            "An accordion that keeps one item open at a time, as uikit:Accordion.",
            [
                new("uikit-accordion/demo", "UikitAccordion/Demo", null, null, null),
                new("uikit-accordion/multiple", "UikitAccordion/Multiple", "Multiple", "Examples", "`Multiple=\"True\"` and `IsBordered=\"False\"`, at `small`."),
            ]),
        new(
            "uikit-async-image", "AsyncImage", "Image",
            CatalogSection.UIKit, "Data display", ["uikit:AsyncImage"],
            null, null,
            "An image loaded from a URI off the UI thread, with loading and fallback content, as uikit:AsyncImage.",
            [
                new("uikit-async-image/demo", "UikitAsyncImage/Demo", null, null, null),
            ]),
        new(
            "uikit-button-group", "ButtonGroup", "Button Group",
            CatalogSection.UIKit, "Buttons", ["uikit:ButtonGroup"],
            null, null,
            "Buttons grouped into one control that reports the selection, as uikit:ButtonGroup.",
            [
                new("uikit-button-group/demo", "UikitButtonGroup/Demo", null, null, "The demo has a group for one choice and one with `Multiple=\"True\"`; each applies the indices its `Click` reports."),
            ]),
        new(
            "uikit-calendar-view", "CalendarView", "Calendar",
            CatalogSection.UIKit, "Forms", ["uikit:CalendarView", "uikit:CalendarViewItem"],
            null, null,
            "A calendar with several months, ranges, disabled days and a years grid, as uikit:CalendarView.",
            [
                new("uikit-calendar-view/demo", "UikitCalendarView/Demo", null, null, null),
                new("uikit-calendar-view/range", "UikitCalendarView/Range", "Range", "Examples", "A range."),
                new("uikit-calendar-view/months", "UikitCalendarView/Months", "Several months", "Examples", "Two months side by side, selecting a range."),
                new("uikit-calendar-view/disabled-days", "UikitCalendarView/DisabledDays", "Disabled days", "Examples", "Disabled weekends and a disabled range of dates."),
            ]),
        new(
            "uikit-color-select", "ColorSelect", "Color Picker, ColorPicker",
            CatalogSection.UIKit, "Forms", ["uikit:ColorSelect"],
            null, null,
            "A color swatch or input field with a palette and HSLA popover, as uikit:ColorSelect.",
            [
                new("uikit-color-select/demo", "UikitColorSelect/Demo", null, null, "The demo shows swatches: a color, a color with a label, and an icon."),
                new("uikit-color-select/field", "UikitColorSelect/Field", "Field", "Examples", "Fields: a color, no color with a placeholder, and one that opens on the HSLA tab."),
            ]),
        new(
            "uikit-date-field", "DateField", "Date Picker, DatePicker",
            CatalogSection.UIKit, "Forms", ["uikit:DateField", "uikit:DateRangePreset"],
            null, null,
            "A date field with ranges, presets, a clear button and the time of day, as uikit:DateField.",
            [
                new("uikit-date-field/demo", "UikitDateField/Demo", null, null, null),
                new("uikit-date-field/range", "UikitDateField/Range", "Range and presets", "Examples", "A range over two months, with presets."),
                new("uikit-date-field/time", "UikitDateField/Time", "Date and time", "Examples", "A date with its time, to the minute and to the second."),
                new("uikit-date-field/presets", "UikitDateField/Presets", "Presets, disabled weekends and plain", "Examples", "Presets, disabled weekends and the `plain` class."),
            ]),
        new(
            "uikit-icon", "Icon", "Icon, IconName",
            CatalogSection.UIKit, "Data display", ["uikit:Icon"],
            null, null,
            "An icon drawn by name, as uikit:Icon.",
            [
                new("uikit-icon/demo", "UikitIcon/Demo", null, null, null),
                new("uikit-icon/gallery", "UikitIcon/Gallery", "Gallery", "Examples", "The icons the theme carries, `IconNames.Bundled`; point at an icon for its name."),
            ]),
        new(
            "uikit-input-group", "InputGroup", "Input Group",
            CatalogSection.UIKit, "Forms", ["uikit:InputGroup", "uikit:InputGroupAddon"],
            null, null,
            "A text field and its addons in one frame, with rows above and below, as uikit:InputGroup.",
            [
                new("uikit-input-group/demo", "UikitInputGroup/Demo", null, null, "The demo shows text addons, an invalid group with a button, and a disabled one."),
                new("uikit-input-group/rows", "UikitInputGroup/Rows", "Rows above and below", "Examples", "A row of text above a search field, and a composer with a counter and a Send button below a multi-line input."),
            ]),
        new(
            "uikit-list-view", "ListView", "List",
            CatalogSection.UIKit, "Data display", ["uikit:ListView", "uikit:ListItem", "uikit:ListSection"],
            null, null,
            "A list with sections, a search field, loading states and confirm and cancel, as uikit:ListView.",
            [
                new("uikit-list-view/demo", "UikitListView/Demo", null, null, null),
                new("uikit-list-view/search", "UikitListView/Search", "Search", "Examples", "`IsSearchable=\"True\"` puts a search field above the rows. The query (`SearchText`) filters the items by their text, or by `SearchFilter`, and selects the first one; Up, Down and Enter work while typing."),
                new("uikit-list-view/loading", "UikitListView/Loading", "Loading", "Examples", "`IsLoading=\"True\"` shows three skeleton rows instead of the rows. An empty list shows `EmptyContent`, or the Inbox icon."),
            ]),
        new(
            "uikit-notification-list", "NotificationList", "Notification, Toast",
            CatalogSection.UIKit, "Feedback", ["uikit:NotificationList", "uikit:NotificationItem"],
            null, null,
            "Notifications stacked per placement, with ids and actions, as uikit:NotificationList.",
            [
                new("uikit-notification-list/demo", "UikitNotificationList/Demo", null, null, null),
                new("uikit-notification-list/placements", "UikitNotificationList/Placements", "Placements", "Examples", "A card at each placement."),
            ]),
        new(
            "uikit-number-input", "NumberInput", "Number Input",
            CatalogSection.UIKit, "Forms", ["uikit:NumberInput"],
            null, null,
            "A numeric field that keeps its text a number and steps by its own rules, as uikit:NumberInput.",
            [
                new("uikit-number-input/demo", "UikitNumberInput/Demo", null, null, "The demo has steps of 0.2 that keep one decimal, an amount grouped by thousands stepped by 100, and a `StepBy` that steps by 0.1 below 1 and by 0.5 above it."),
            ]),
        new(
            "uikit-pagination", "Pagination", "Pagination",
            CatalogSection.UIKit, "Navigation", ["uikit:Pagination"],
            null, null,
            "Page buttons built from a page count, with ellipses and their page menus, as uikit:Pagination.",
            [
                new("uikit-pagination/demo", "UikitPagination/Demo", null, null, "The demo has ten pages around page 5, and 50 pages with `VisiblePages=\"7\"` in `small`."),
                new("uikit-pagination/compact", "UikitPagination/Compact", "Compact", "Examples", "`compact`, at the default size and with `small`."),
            ]),
        new(
            "uikit-range-slider", "RangeSlider", "Slider, Range",
            CatalogSection.UIKit, "Forms", ["uikit:RangeSlider"],
            null, null,
            "A slider with two thumbs or a logarithmic scale, as uikit:RangeSlider.",
            [
                new("uikit-range-slider/demo", "UikitRangeSlider/Demo", null, null, "The demo shows a range, horizontal and vertical."),
                new("uikit-range-slider/logarithmic", "UikitRangeSlider/Logarithmic", "Logarithmic", "Examples", "A single value on a logarithmic scale from 0.25x to 4x."),
            ]),
        new(
            "uikit-resizable-panel-group", "ResizablePanelGroup", "Resizable, ResizablePanel",
            CatalogSection.UIKit, "Layout", ["uikit:ResizablePanelGroup", "uikit:ResizablePanel"],
            null, null,
            "Panels side by side with resize handles between them, as uikit:ResizablePanelGroup.",
            [
                new("uikit-resizable-panel-group/demo", "UikitResizablePanelGroup/Demo", null, null, "The demo has a left panel limited to 120..240, a vertical group in the middle and a right panel."),
                new("uikit-resizable-panel-group/programmatic", "UikitResizablePanelGroup/Programmatic", "Programmatic", "Examples", "Hiding the left panel, `ResizePanel`, and the sizes `Resized` reports."),
            ]),
        new(
            "uikit-select", "Select", "Select, Combobox",
            CatalogSection.UIKit, "Forms", ["uikit:Select", "uikit:SelectGroup"],
            null, null,
            "A select with a search field, sections, multiple selection and a footer, as uikit:Select.",
            [
                new("uikit-select/demo", "UikitSelect/Demo", null, null, "The demo has a search field: type to filter the fruits."),
                new("uikit-select/groups", "UikitSelect/Groups", "Groups", "Examples", "Sections, with the search field."),
                new("uikit-select/clear", "UikitSelect/Clear", "Clear", "Examples", "A clear button while there is a value, and a title prefix with an icon in place of the chevron."),
                new("uikit-select/multiple", "UikitSelect/Multiple", "Multiple", "Examples", "Multiple selection with a search field and a clear button."),
                new("uikit-select/footer", "UikitSelect/Footer", "Footer", "Examples", "A footer button that adds what was typed in the search field."),
                new("uikit-select/trigger", "UikitSelect/Trigger", "Custom trigger", "Examples", "A trigger template: an icon, the title or the placeholder, and the chevron."),
            ]),
        new(
            "uikit-sheet", "Sheet", "Sheet, Drawer",
            CatalogSection.UIKit, "Overlays", ["uikit:Sheet"],
            null, null,
            "A panel opened from code that slides in from a side over the dimmed window, as uikit:Sheet.",
            [
                new("uikit-sheet/demo", "UikitSheet/Demo", null, null, "The demo opens a sheet from each side, and one at half the window's width; the footer's buttons call `Close`."),
            ]),
        new(
            "uikit-sidebar", "Sidebar", "Sidebar",
            CatalogSection.UIKit, "Navigation", ["uikit:Sidebar", "uikit:SidebarGroup", "uikit:SidebarMenu", "uikit:SidebarMenuItem"],
            null, null,
            "A sidebar with menus, groups and submenus, collapsing to icons or off canvas, as uikit:Sidebar.",
            [
                new("uikit-sidebar/demo", "UikitSidebar/Demo", null, null, "The demo has a header and its company menu, two groups, a submenu with a switch, a badge, a disabled item, a footer and a toggle button; a click makes an item the active one."),
                new("uikit-sidebar/pane", "UikitSidebar/Pane", "In a SplitView", "Examples", "`uikit:Sidebar` as a `SplitView`'s pane in `CompactInline`: closing the pane collapses the menu to its icons."),
            ]),
        new(
            "uikit-table", "Table", "Table",
            CatalogSection.UIKit, "Data display", ["uikit:Table", "uikit:TableRow", "uikit:TableCell"],
            null, null,
            "A table written out row by row, with column spans, a footer and a caption, as uikit:Table.",
            [
                new("uikit-table/demo", "UikitTable/Demo", null, null, "The demo has a header cell over two columns, tags in the cells, a footer whose total spans three columns, and a caption."),
                new("uikit-table/striped", "UikitTable/Striped", "Striped", "Examples", "Bordered, striped and `small`."),
            ]),
        new(
            "uikit-text-label", "TextLabel", "Label",
            CatalogSection.UIKit, "Data display", ["uikit:TextLabel"],
            null, null,
            "A label with secondary text, highlighted matches and a mask, as uikit:TextLabel.",
            [
                new("uikit-text-label/demo", "UikitTextLabel/Demo", null, null, null),
                new("uikit-text-label/highlights", "UikitTextLabel/Highlights", "Highlights", "Examples", "Type in the field to highlight the matches in both labels; Mask hides their text."),
            ]),
        new(
            "uikit-time-field", "TimeField", "Time Field, Time Picker",
            CatalogSection.UIKit, "Forms", ["uikit:TimeField"],
            null, null,
            "A time field edited segment by segment, as uikit:TimeField.",
            [
                new("uikit-time-field/demo", "UikitTimeField/Demo", null, null, null),
                new("uikit-time-field/states", "UikitTimeField/States", "Sizes and states", "Examples", "A small and a large field, a disabled one and an invalid one."),
            ]),
        new(
            "uikit-title-bar", "TitleBar", "Title Bar",
            CatalogSection.UIKit, "Layout", ["uikit:TitleBar"],
            null, null,
            "A title bar with content of your own at the top of the window, as uikit:TitleBar.",
            [
                new("uikit-title-bar/demo", "UikitTitleBar/Demo", null, null, null),
            ]),
        new(
            "uikit-toggle-group", "ToggleGroup", "Toggle Group",
            CatalogSection.UIKit, "Buttons", ["uikit:ToggleGroup"],
            null, null,
            "Toggle buttons in a group that reports their states, as uikit:ToggleGroup.",
            [
                new("uikit-toggle-group/demo", "UikitToggleGroup/Demo", null, null, "The demo has a group with labels, and outlined and `segmented` groups with icons."),
            ]),
        new(
            "uikit-toolbar", "Toolbar", "Toolbar",
            CatalogSection.UIKit, "Navigation", ["uikit:Toolbar", "uikit:ToolbarGroup", "uikit:ToolbarSpacer"],
            null, null,
            "A row of any controls that share one size and the arrow keys, as uikit:Toolbar.",
            [
                new("uikit-toolbar/demo", "UikitToolbar/Demo", null, null, "The demo has two groups, a separator, a `TextBox`, a spacer and a primary button that keeps its own look."),
            ]),
        new(
            "uikit-tree", "Tree", "Tree",
            CatalogSection.UIKit, "Data display", ["uikit:Tree", "uikit:TreeItem"],
            null, null,
            "A virtualized tree for any number of items, as uikit:Tree.",
            [
                new("uikit-tree/demo", "UikitTree/Demo", null, null, null),
                new("uikit-tree/virtualized", "UikitTree/Virtualized", "Virtualized", "Examples", "Fifty packages of two hundred files each: only the rows in view are realized."),
            ]),
        new(
            "virtual-list", "Virtual List", "VirtualList",
            CatalogSection.Avalonia, "Data display", ["ListBox", "VirtualizingStackPanel"],
            null, null,
            "A virtualized list with the List's rows, as ListBox over a VirtualizingStackPanel.",
            [
                new("virtual-list/demo", "VirtualList/Demo", null, null, null),
                new("virtual-list/scroll-to", "VirtualList/ScrollTo", "Scroll to an item", "Scroll to an item", "`ScrollToItem`, an extension method for `ListBox` and any other `ItemsControl` (namespace `AvaloniaUIKit`), scrolls to an item by its index, also one the panel has not realized yet. `ScrollStrategy.Center` puts the item in the middle of the list, as far as the list allows; the other strategies bring an item out of view to the nearer edge and leave an item in view where it is. A call made before the list is laid out waits for the layout."),
            ]),
    ];

    /// <summary>The site's code colors by GPUI Kit theme name (app/style.css, app/styles/themes.g.css).</summary>
    public static IReadOnlyDictionary<string, CodePalette> CodePalettes { get; } = new Dictionary<string, CodePalette>(StringComparer.OrdinalIgnoreCase)
    {
        ["Default Light"] = new(0xFFFFFFFF, 0xFF000000, 0xFF0433FF, 0xFF036A07, 0xFF8A8A8A, 0xFF0000A2, 0xFF571AB7),
        ["Default Dark"] = new(0xFF151515, 0xFFCACCCA, 0xFF87B1F6, 0xFFA3E09F, 0xFF8D8D8D, 0xFFB3C5F3, 0xFFCBA6F7),
        ["Adventure"] = new(0xFF040404, 0xFFFEFFFF, 0xFF417AB3, 0xFF5DA602, 0xFF5D6165, 0xFF5DA602, 0xFFEEBB6E),
        ["Adventure Time"] = new(0xFF1F1D45, 0xFFF8DCC0, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Alduin"] = new(0xFF000000, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Asciinema"] = new(0xFF121314, 0xFFCCCCCC, 0xFFDD3C69, 0xFF4EBF22, 0xFF5D5D5D, 0xFF54E1B9, 0xFF26B0D7),
        ["Aurora Light"] = new(0xFFFFFFFF, 0xFF020617, 0xFF0433FF, 0xFF036A07, 0xFF007FFF, 0xFF0000A2, 0xFF6F42C1),
        ["Ayu Dark"] = new(0xFF0D1016, 0xFFBFBDB6, 0xFFFF8F3F, 0xFFA9D94B, 0xFF8C8B88, 0xFFFFB353, 0xFF59C2FF),
        ["Ayu Light"] = new(0xFFFCFCFC, 0xFF5C6773, 0xFFFA8D3E, 0xFF86B300, 0xFF898D90, 0xFFF2AD48, 0xFF389EE6),
        ["Catppuccin Frappe"] = new(0xFF232634, 0xFFC6D0F5, 0xFFE78284, 0xFFA6D189, 0xFF51576D, 0xFF8CAAEE, 0xFF8CAAEE),
        ["Catppuccin Latte"] = new(0xFFEFF1F5, 0xFF4C4F69, 0xFF8839EF, 0xFF85DC78, 0xFF7C7F93, 0xFF1E66F5, 0xFFDF8E1D),
        ["Catppuccin Macchiato"] = new(0xFF1E2030, 0xFFCAD3F5, 0xFFF5BDE6, 0xFFA6DA95, 0xFFB8C0E0, 0xFF8AADF4, 0xFF8AADF4),
        ["Catppuccin Mocha"] = new(0xFF181825, 0xFFCDD6F4, 0xFFF5C2E7, 0xFFA6E3A1, 0xFF6C7086, 0xFF89B4FA, 0xFF89B4FA),
        ["Everforest Dark"] = new(0xFF262E34, 0xFFD3C6AA, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Everforest Light"] = new(0xFFFEFCEE, 0xFF5F6D75, 0xFFE67E80, 0xFFA7C080, 0xFF959A9D, 0xFFA7C080, 0xFF7FBBB3),
        ["Fahrenheit"] = new(0xFF000000, 0xFFFFFFCE, 0xFFCB4A05, 0xFFCC734D, 0xFF828282, 0xFFFD9F4D, 0xFFCDA074),
        ["Flexoki Dark"] = new(0xFF100F0F, 0xFFCECDC3, 0xFF879A39, 0xFF3AA99F, 0xFF575653, 0xFFDA702C, 0xFFD0A215),
        ["Flexoki Light"] = new(0xFFFFFCF0, 0xFF100F0F, 0xFF66800B, 0xFF24837B, 0xFFB7B5AC, 0xFFBC5215, 0xFFAD8301),
        ["Gruvbox Dark"] = new(0xFF1D2021, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Gruvbox Light"] = new(0xFFFBF1C7, 0xFF3C3836, 0xFFCC241D, 0xFF79740E, 0xFF928374, 0xFFD79921, 0xFFB57614),
        ["Harper"] = new(0xFF010101, 0xFFA8A49D, 0xFFFF5874, 0xFF489E48, 0xFF726E69, 0xFFF8B63F, 0xFFB296C6),
        ["Hybrid Dark"] = new(0xFF000000, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Hybrid Light"] = new(0xFFE4E4E4, 0xFF1C1C1C, 0xFF5F1C51, 0xFF005F00, 0xFF5F5F5F, 0xFF005F87, 0xFF5F1C51),
        ["Jellybeans"] = new(0xFF000000, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Kibble"] = new(0xFF0E100A, 0xFFF7F7F7, 0xFFC70031, 0xFF2BCF13, 0xFF726E69, 0xFFC7A302, 0xFF3449D1),
        ["macOS Classic Dark"] = new(0xFF131313, 0xFFCACCCA, 0xFF87B1F6, 0xFFA3E09F, 0xFF9D9D9D, 0xFFB3C5F3, 0xFFCBA6F7),
        ["macOS Classic Light"] = new(0xFFFFFFFF, 0xFF000000, 0xFF0433FF, 0xFF036A07, 0xFF007FFF, 0xFF0000A2, 0xFF6F42C1),
        ["Mellifluous Dark"] = new(0xFF1A1A1A, 0xFFABB2BF, 0xFFE06C75, 0xFF828040, 0xFF828997, 0xFFD19A66, 0xFF929292),
        ["Mellifluous Light"] = new(0xFFE7E7E7, 0xFF383A42, 0xFFE06C75, 0xFF828040, 0xFFA0A0A0, 0xFFCBAA89, 0xFF727272),
        ["Molokai Dark"] = new(0xFF000000, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Molokai Light"] = new(0xFFFEFAF9, 0xFF0A0A0A, 0xFFE14775, 0xFF269D69, 0xFF767676, 0xFFE14775, 0xFF1C8CA8),
        ["Solarized Dark"] = new(0xFF002B36, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Solarized Light"] = new(0xFFFDF6E3, 0xFF586E75, 0xFFDC322F, 0xFF859900, 0xFF93A1A1, 0xFF268BD2, 0xFF2AA198),
        ["Spaceduck"] = new(0xFF0F111B, 0xFFECF0C1, 0xFFC86D8C, 0xFF5CCC96, 0xFF4B6479, 0xFF089CC5, 0xFF089CC5),
        ["Tokyo Moon"] = new(0xFF222436, 0xFFC0CAF5, 0xFFED8796, 0xFFC3E88D, 0xFF6E738D, 0xFF82AAFF, 0xFF86E1FC),
        ["Tokyo Night"] = new(0xFF1A1B26, 0xFFC0CAF5, 0xFFF7768E, 0xFF9ECE6A, 0xFF565F89, 0xFF7AA2F7, 0xFF7DCFFF),
        ["Tokyo Storm"] = new(0xFF24283B, 0xFFB0B9E2, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
        ["Twilight"] = new(0xFF000000, 0xFFDDDDDD, 0xFFE19773, 0xFF76BA53, 0xFF9E9E9E, 0xFFE1D797, 0xFFA86D3B),
    };
}
