//! Converts the Lucide icons GPUI Kit ships to filled outlines for Avalonia.
//!
//! GPUI renders an icon by rasterizing its SVG (24x24, 2px round strokes) with
//! resvg. Avalonia's PathIcon fills a geometry, so each stroke is expanded to
//! its outline here with the same stroker resvg uses (tiny-skia).
use anyhow::{Context as _, Result};
use std::{fmt::Write as _, path::Path};
use tiny_skia_path::PathSegment;

/// The icons the themes draw, by GPUI IconName file name.
pub const ICONS: [&str; 9] = [
    "check",
    "minus",
    "plus",
    "chevron-down",
    "chevron-right",
    "chevron-up",
    "loader",
    "copy",
    "external-link",
];

fn outline(svg: &[u8]) -> Result<String> {
    let tree = usvg::Tree::from_data(svg, &usvg::Options::default())?;
    let mut data = String::new();
    // Zero-area anchors at (0,0) and (24,24): they paint nothing but make the
    // geometry's bounds the icon's 24x24 box, so a stretched Viewbox scales
    // the icon exactly as GPUI scales the SVG.
    data.push_str("F1 M0,0L0,0Z M24,24L24,24Z");
    collect(tree.root(), &mut data)?;
    Ok(data)
}

fn collect(group: &usvg::Group, data: &mut String) -> Result<()> {
    for node in group.children() {
        match node {
            usvg::Node::Group(group) => collect(group, data)?,
            usvg::Node::Path(path) => {
                let transform = path.abs_transform();
                if let Some(stroke) = path.stroke() {
                    let outline = path
                        .data()
                        .stroke(&stroke.to_tiny_skia(), 1.0)
                        .context("stroking an icon path")?
                        .transform(transform)
                        .context("transforming an icon path")?;
                    append(&outline, data);
                }
                if path.fill().is_some() {
                    let fill = path.data().clone().transform(transform).context("transforming")?;
                    append(&fill, data);
                }
            }
            _ => {}
        }
    }
    Ok(())
}

fn n(v: f32) -> String {
    let s = format!("{:.4}", v);
    let s = s.trim_end_matches('0').trim_end_matches('.');
    if s == "-0" { "0".into() } else { s.into() }
}

fn append(path: &tiny_skia_path::Path, data: &mut String) {
    for segment in path.segments() {
        let _ = match segment {
            PathSegment::MoveTo(p) => write!(data, " M{},{}", n(p.x), n(p.y)),
            PathSegment::LineTo(p) => write!(data, " L{},{}", n(p.x), n(p.y)),
            PathSegment::QuadTo(c, p) => write!(data, " Q{},{} {},{}", n(c.x), n(c.y), n(p.x), n(p.y)),
            PathSegment::CubicTo(c1, c2, p) => write!(
                data,
                " C{},{} {},{} {},{}",
                n(c1.x), n(c1.y), n(c2.x), n(c2.y), n(p.x), n(p.y)
            ),
            PathSegment::Close => write!(data, " Z"),
        };
    }
}

pub fn write_xaml(root: &Path) -> Result<()> {
    let icons = root.join("reference/vendor/gpui-kit/crates/assets/assets/icons");
    let mut xaml = String::from(
        "<!--\n  DO NOT EDIT. Generated by `reference generate` from the Lucide icons GPUI Kit\n  ships (crates/assets/assets/icons), stroked to filled outlines.\n  Lucide is ISC licensed: see Icons/LUCIDE-LICENSE.txt.\n-->\n<ResourceDictionary xmlns=\"https://github.com/avaloniaui\"\n                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">\n",
    );
    for name in ICONS {
        let svg = std::fs::read(icons.join(format!("{name}.svg")))
            .with_context(|| format!("reading icon {name}"))?;
        let key = format!("Gpui.Icon.{}", crate::tokens::pascal(name));
        let _ = writeln!(xaml, "  <StreamGeometry x:Key=\"{key}\">{}</StreamGeometry>", outline(&svg)?);
    }
    xaml.push_str("</ResourceDictionary>\n");
    let out = root.join("src/AvaloniaUIKit/Themes/Icons/Lucide.g.axaml");
    std::fs::create_dir_all(out.parent().unwrap())?;
    std::fs::write(out, xaml)?;
    Ok(())
}
