//! Dumps the resolved GPUI Kit theme: every ThemeColor field, the scalars the
//! components read, the motion tokens, and the derived colors the components
//! compute while painting (see `derived.rs`).
use crate::harness::Harness;
use anyhow::Result;
use gpui_kit::{
    Hsla, Rgba,
    component::{ActiveTheme as _, Theme, ThemeMode, scroll::ScrollbarMode},
};
use serde_json::{Map, Value, json};

pub fn hex(color: Hsla) -> String {
    let c = Rgba::from(color);
    let to8 = |v: f32| (v * 255.0).round() as u8;
    format!(
        "#{:02x}{:02x}{:02x}{:02x}",
        to8(c.r),
        to8(c.g),
        to8(c.b),
        to8(c.a)
    )
}

fn float_rgba(color: Hsla) -> Value {
    let c = Rgba::from(color);
    json!([c.r, c.g, c.b, c.a])
}

fn mode_dump(harness: &mut Harness, mode: ThemeMode) -> Result<Value> {
    harness.set_theme(mode, ScrollbarMode::Hover);
    harness.cx.update(|cx| -> Result<Value> {
        let theme: &Theme = cx.theme();
        let colors = serde_json::to_value(theme.colors)?;
        let mut float_colors = Map::new();
        let mut hex_colors = Map::new();
        if let Value::Object(map) = &colors {
            for (key, _) in map {
                // Re-read each field as Hsla through serde so no field is missed.
                let single: Value = map[key].clone();
                if let Value::String(s) = &single {
                    hex_colors.insert(key.clone(), Value::String(s.clone()));
                }
            }
        }
        // Exact float values for the fields, via a JSON round trip of Hsla fields.
        let derived = crate::derived::derived(theme);
        let mut derived_hex = Map::new();
        for (name, color) in &derived {
            derived_hex.insert(name.clone(), Value::String(hex(*color)));
            float_colors.insert(name.clone(), float_rgba(*color));
        }
        let motion = &theme.motion;
        Ok(json!({
            "mode": format!("{:?}", theme.mode),
            "colors": hex_colors,
            "derived": derived_hex,
            "derived_float": float_colors,
            "scalars": {
                "font_size": f32::from(theme.font_size),
                "radius": f32::from(theme.radius),
                "radius_lg": f32::from(theme.radius_lg),
                "shadow": theme.shadow,
                "focus_ring": theme.focus_ring,
            },
            "motion": format!("{motion:?}"),
        }))
    })
}

pub fn dump(harness: &mut Harness) -> Result<Value> {
    let light = mode_dump(harness, ThemeMode::Light)?;
    let dark = mode_dump(harness, ThemeMode::Dark)?;
    Ok(json!({
        "gpui_kit": crate::GPUI_KIT_REV,
        "light": light,
        "dark": dark,
    }))
}

/// `button_primary_hover` -> `ButtonPrimaryHover`; `group-hover` -> `GroupHover`.
pub fn pascal(segment: &str) -> String {
    segment
        .split(['_', '-'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// The Avalonia resource key for a dumped color name.
pub fn resource_key(name: &str) -> String {
    let segments: Vec<String> = name.split('.').map(pascal).collect();
    format!("UIKit.{}", segments.join("."))
}

/// `#rrggbbaa` -> Avalonia's `#AARRGGBB`.
fn avalonia_color(hex: &str) -> String {
    let h = hex.trim_start_matches('#');
    format!("#{}{}", &h[6..8], &h[0..6]).to_uppercase()
}

fn dictionary(mode: &Value) -> String {
    let mut out = String::new();
    let mut entries: Vec<(String, String)> = Vec::new();
    for (name, value) in mode["colors"].as_object().into_iter().flatten() {
        entries.push((resource_key(name), value.as_str().unwrap_or_default().to_string()));
    }
    for (name, value) in mode["derived"].as_object().into_iter().flatten() {
        entries.push((resource_key(name), value.as_str().unwrap_or_default().to_string()));
    }
    for (key, hex) in entries {
        let color = avalonia_color(&hex);
        out.push_str(&format!("      <Color x:Key=\"{key}.Color\">{color}</Color>\n"));
        out.push_str(&format!("      <SolidColorBrush x:Key=\"{key}\" Color=\"{color}\" />\n"));
    }
    out
}

/// Writes the theme dictionaries the Avalonia theme merges.
pub fn write_xaml(root: &std::path::Path, tokens: &Value) -> Result<()> {
    let xaml = format!(
        r#"<!--
  DO NOT EDIT. Generated by `reference generate` from GPUI Kit {rev}.
  Every color is the value GPUI Kit resolves for its Default Light / Default Dark
  theme, including the colors its components derive while painting.
-->
<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
{light}    </ResourceDictionary>
    <ResourceDictionary x:Key="Dark">
{dark}    </ResourceDictionary>
  </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
"#,
        rev = crate::GPUI_KIT_REV,
        light = dictionary(&tokens["light"]),
        dark = dictionary(&tokens["dark"]),
    );
    let path = root.join("src/AvaloniaUIKit/Themes/Tokens/Colors.g.axaml");
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(&path, xaml)?;
    Ok(())
}
