/**
 * Generates samples/AvaloniaUIKit.Demos/DemoRegistry.g.cs from
 * samples/AvaloniaUIKit.Demos/Demos/<Component>/<Name>.axaml: a partial class
 * per demo (so a demo needs no code-behind unless it has handlers) and the
 * table of factories by id (`<component-slug>/<name-slug>`). See docs/site.md.
 *
 *   bun sites/scripts/demo-registry.ts          # write
 *   bun sites/scripts/demo-registry.ts --check  # fail if the file is stale
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "../..")
const demosDir = path.join(root, "samples/AvaloniaUIKit.Demos/Demos")
const output = path.join(root, "samples/AvaloniaUIKit.Demos/DemoRegistry.g.cs")

export const kebab = (name: string) =>
  name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2").toLowerCase()

export interface DemoFile {
  /** `button/demo` */
  id: string
  /** `ButtonDemo` */
  className: string
  /** Absolute path of the .axaml. */
  file: string
}

export function listDemos(): DemoFile[] {
  const demos: DemoFile[] = []
  for (const component of readdirSync(demosDir, { withFileTypes: true })) {
    if (!component.isDirectory()) continue
    for (const entry of readdirSync(path.join(demosDir, component.name))) {
      if (!entry.endsWith(".axaml")) continue
      const name = entry.slice(0, -".axaml".length)
      for (const part of [component.name, name]) {
        if (!/^[A-Z][A-Za-z0-9]*$/.test(part)) {
          throw new Error(`${component.name}/${entry}: directory and file names must be PascalCase identifiers`)
        }
      }
      const file = path.join(demosDir, component.name, entry)
      const className = `${component.name}${name}`
      const expected = `AvaloniaUIKit.Demos.${className}`
      const xClass = readFileSync(file, "utf8").match(/x:Class="([^"]+)"/)?.[1]
      if (xClass !== expected) {
        throw new Error(`${component.name}/${entry}: x:Class must be "${expected}" (found ${xClass ?? "none"})`)
      }
      demos.push({ id: `${kebab(component.name)}/${kebab(name)}`, className, file })
    }
  }
  return demos.sort((a, b) => a.id.localeCompare(b.id, "en"))
}

function render(demos: DemoFile[]): string {
  const classes = demos
    .map(
      (demo) =>
        `public sealed partial class ${demo.className} : UserControl\n{\n    public ${demo.className}() => AvaloniaXamlLoader.Load(this);\n}\n`
    )
    .join("\n")
  const table = demos
    .map((demo) => `        ["${demo.id}"] = static () => new ${demo.className}(),`)
    .join("\n")
  return `// <auto-generated/>
// Generated by \`bun sites/scripts/demo-registry.ts\` from Demos/**/*.axaml. Do not edit.
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaloniaUIKit.Demos;

${classes}
public static partial class DemoRegistry
{
    /// <summary>Every demo by id (\`&lt;component&gt;/&lt;name&gt;\`), in id order.</summary>
    public static IReadOnlyDictionary<string, Func<Control>> Factories { get; } = new Dictionary<string, Func<Control>>
    {
${table}
    };
}
`
}

if (import.meta.main) {
  const demos = listDemos()
  const text = render(demos)
  if (process.argv.includes("--check")) {
    let current = ""
    try {
      current = readFileSync(output, "utf8")
    } catch {}
    if (current !== text) {
      console.error(`${path.relative(root, output)} is stale: run \`bun sites/scripts/demo-registry.ts\``)
      process.exit(1)
    }
    console.log(`${path.relative(root, output)} is up to date (${demos.length} demos).`)
  } else {
    writeFileSync(output, text)
    console.log(`Wrote ${path.relative(root, output)} (${demos.length} demos).`)
  }
}
