#!/usr/bin/env python3
"""Generates src/AvaloniaUIKit/Themes/Controls/DropDownButton.axaml.

GPUI Kit's Button with `dropdown_caret(true)` (crates/component/src/button/button.rs)
is the Button with a caret after its content: the content row spreads its
children (justify_between) with the size's gap (4px for XSmall and Small,
8px otherwise), and the caret (select.rs Caret: 12/14/16/16px) is the normal
foreground at 75% in every state. DropDownButton takes the Button theme
(BasedOn) and replaces only the template, so the variants, outline, sizes,
compact, rounded and selected classes are the Button's. The caret colors are
generated from GPUI Kit (UIKit.Button.<Variant>[.Outline].Caret).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/AvaloniaUIKit/Themes/Controls/DropDownButton.axaml"

VARIANTS = ["default", "primary", "secondary", "danger", "warning", "success", "info", "ghost", "link", "text"]
# Size: caret (Caret::new), gap (button.rs: gap_1 for XSmall and Small, gap_2 otherwise).
SIZES = {
    "xsmall": (12, 4),
    "small": (14, 4),
    "medium": (16, 8),
    "large": (16, 8),
}


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_"))


def selector(variant: str, outline: bool) -> str:
    parts = "^"
    if variant != "default":
        parts += f".{variant}"
    if outline:
        parts += ".outline"
    return parts


lines: list[str] = []
w = lines.append

w("<!--")
w("  DO NOT EDIT. Generated by scripts/gen_dropdown_button_theme.py.")
w("")
w("  GPUI Kit Button::dropdown_caret(true) -> DropDownButton (crates/component/src/button/button.rs).")
w("  The Button theme with a caret after the content: the Button's classes (variants,")
w("  outline, compact, selected, sizes, rounded) apply as they are. The content sits")
w("  at the start and the caret at the end (justify_between), the size's gap apart;")
w("  the caret keeps the normal foreground at 75% while hovered, pressed, selected or")
w("  disabled, as GPUI colors it apart from the button's text. An open flyout shows")
w("  the selected look; give the MenuFlyout Placement=\"BottomEdgeAlignedLeft\".")
w("-->")
w('<Styles xmlns="https://github.com/avaloniaui"')
w('        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
w('  <Styles.Resources>')
w('    <ControlTheme x:Key="{x:Type DropDownButton}" TargetType="DropDownButton" BasedOn="{StaticResource {x:Type Button}}">')
w('      <Setter Property="HorizontalContentAlignment" Value="Left" />')
w('      <Setter Property="Template">')
w('        <ControlTemplate>')
w('          <Panel>')
w('            <Border Name="PART_Frame"')
w('                    BackgroundSizing="OuterBorderEdge"')
w('                    Background="{TemplateBinding Background}"')
w('                    BorderBrush="{TemplateBinding BorderBrush}"')
w('                    BorderThickness="{TemplateBinding BorderThickness}"')
w('                    CornerRadius="{TemplateBinding CornerRadius}"')
w('                    Padding="{TemplateBinding Padding}">')
_, gap = SIZES["medium"]
w(f'              <Grid Name="PART_Layout" ColumnDefinitions="*,Auto" ColumnSpacing="{gap}">')
w('                <ContentPresenter Name="PART_ContentPresenter"')
w('                                  Content="{TemplateBinding Content}"')
w('                                  ContentTemplate="{TemplateBinding ContentTemplate}"')
w('                                  HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"')
w('                                  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"')
w('                                  Foreground="{TemplateBinding Foreground}"')
w('                                  LineHeight="17.5"')
w('                                  TextWrapping="NoWrap"')
w('                                  TextTrimming="CharacterEllipsis"')
w('                                  RecognizesAccessKey="True" />')
caret, _ = SIZES["medium"]
w(f'                <PathIcon Name="PART_Caret" Grid.Column="1" Width="{caret}" Height="{caret}" VerticalAlignment="Center"')
w('                          Data="{StaticResource UIKit.Icon.ChevronDown}" />')
w('              </Grid>')
w('            </Border>')
w('            <!-- focus_ring (styled.rs): a 3px band outside the border, in ring at 50%. -->')
w('            <Border Name="PART_FocusRing" Margin="-3" BorderThickness="3"')
w('                    CornerRadius="7.5"')
w('                    BorderBrush="{DynamicResource UIKit.FocusRing}"')
w('                    IsVisible="False" IsHitTestVisible="False" />')
w('          </Panel>')
w('        </ControlTemplate>')
w('      </Setter>')
w('')
for size, (caret, gap) in SIZES.items():
    if size == "medium":
        continue
    w(f'      <Style Selector="^.{size} /template/ PathIcon#PART_Caret">')
    w(f'        <Setter Property="Width" Value="{caret}" />')
    w(f'        <Setter Property="Height" Value="{caret}" />')
    w('      </Style>')
    w(f'      <Style Selector="^.{size} /template/ Grid#PART_Layout">')
    w(f'        <Setter Property="ColumnSpacing" Value="{gap}" />')
    w('      </Style>')
w('')
w('      <!-- The caret: the normal foreground at 75%, in every state. -->')
for variant in VARIANTS:
    for outline in [False, True]:
        key = f"UIKit.Button.{pascal(variant)}{'.Outline' if outline else ''}.Caret"
        w(f'      <Style Selector="{selector(variant, outline)} /template/ PathIcon#PART_Caret">')
        w(f'        <Setter Property="Foreground" Value="{{DynamicResource {key}}}" />')
        w('      </Style>')
w('    </ControlTheme>')
w('  </Styles.Resources>')
w('</Styles>')

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
