#!/usr/bin/env python3
"""Generates src/AvaloniaUIKit/Themes/Controls/SplitView.axaml.

SplitView's template differs per PanePlacement only in which grid cell and
edge the pane takes, so the four templates are written out from one.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/AvaloniaUIKit/Themes/Controls/SplitView.axaml"

def template(side):
    horizontal = side in ("left", "right")
    first = side in ("left", "top")
    defs = "ColumnDefinitions" if horizontal else "RowDefinitions"
    length = "PaneColumnGridLength" if horizontal else "PaneRowGridLength"
    pane_def = f'<{"ColumnDefinition Width" if horizontal else "RowDefinition Height"}="{{Binding $parent[SplitView].TemplateSettings.{length}}}" />'
    star_def = f'<{"ColumnDefinition Width" if horizontal else "RowDefinition Height"}="*" />'
    idx = "Grid.Column" if horizontal else "Grid.Row"
    align = ("HorizontalAlignment" if horizontal else "VerticalAlignment") + '="' + {"left": "Left", "right": "Right", "top": "Top", "bottom": "Bottom"}[side] + '"'
    pane_index = 0 if first else 1
    content_index = 1 if first else 0
    defs_xml = (pane_def + star_def) if first else (star_def + pane_def)
    return f'''      <Setter Property="Template">
        <ControlTemplate>
          <Grid Name="Container" Background="{{TemplateBinding Background}}" ClipToBounds="True">
            <Grid.{defs}>
              {defs_xml.replace("/><", "/>" + chr(10) + "              <")}
            </Grid.{defs}>
            <Panel Name="PART_PaneRoot" {idx}="{pane_index}" {align} ZIndex="100" ClipToBounds="True">
              <Panel.RenderTransform>
                <TranslateTransform />
              </Panel.RenderTransform>
              <!-- The sheet's shadow: a Border with a one-sided border draws no BoxShadow. -->
              <Border Name="PART_PaneShadow" IsHitTestVisible="False" />
              <Border Name="PART_PaneSurface"
                      Background="{{TemplateBinding PaneBackground}}"
                      BackgroundSizing="OuterBorderEdge"
                      BorderBrush="{{DynamicResource UIKit.SidebarBorder}}"
                      TextElement.Foreground="{{DynamicResource UIKit.SidebarForeground}}">
                <ContentPresenter Name="PART_PanePresenter"
                                  Content="{{TemplateBinding Pane}}"
                                  ContentTemplate="{{TemplateBinding PaneTemplate}}" />
              </Border>
            </Panel>
            <Panel Name="ContentRoot" {idx}="{content_index}">
              <ContentPresenter Name="PART_ContentPresenter"
                                Content="{{TemplateBinding Content}}"
                                ContentTemplate="{{TemplateBinding ContentTemplate}}" />
              <Rectangle Name="LightDismissLayer" Fill="Transparent" IsVisible="False" />
            </Panel>
          </Grid>
        </ControlTemplate>
      </Setter>'''

def spans(side):
    horizontal = side in ("left", "right")
    first = side in ("left", "top")
    idx = "Grid.Column" if horizontal else "Grid.Row"
    span = "Grid.ColumnSpan" if horizontal else "Grid.RowSpan"
    pane_index = 0 if first else 1
    out = []
    # Overlay modes: the pane spans the content too; inline modes: side by side.
    out.append(f'''      <Style Selector="^:overlay /template/ Panel#PART_PaneRoot, ^:compactoverlay /template/ Panel#PART_PaneRoot">
        <Setter Property="{idx}" Value="0" />
        <Setter Property="{span}" Value="2" />
      </Style>''')
    out.append(f'''      <Style Selector="^:overlay /template/ Panel#ContentRoot">
        <Setter Property="{idx}" Value="0" />
        <Setter Property="{span}" Value="2" />
      </Style>''')
    return "\n".join(out)

SIDES = ["left", "right", "top", "bottom"]
BORDER = {"left": "0,0,1,0", "right": "1,0,0,0", "top": "0,0,0,1", "bottom": "0,1,0,0"}
EDGE = {"left": "Left", "right": "Right", "top": "Top", "bottom": "Bottom"}
INWARD = {"left": "Right", "right": "Left", "top": "Bottom", "bottom": "Top"}

lines = []
w = lines.append
w('''<!--
  DO NOT EDIT. Generated by scripts/gen_splitview_theme.py.

  GPUI Kit Sidebar (crates/component/src/sidebar) -> SplitView in its inline
  modes, and the surface of GPUI Kit's Sheet (sheet.rs) in its overlay mode.

  DisplayMode picks GPUI's collapsible mode: CompactInline is Icon (closed:
  48px, CompactPaneLength), Inline is Offcanvas (closed: 0), Inline with
  IsPaneOpen="True" is None. The pane opens to OpenPaneLength (GPUI's 255px
  default). The pane's width moves over 200ms (ease-in-out-cubic) while the
  surface inside snaps to its new width: on the window's side of the pane in
  the compact modes, against the content in Inline (so it slides out). The
  surface paints PaneBackground with a 1px border on the content side.

  Overlay is the sheet: the surface (background, border on the inner edge,
  shadow_xl) slides 100px in over 150ms when it opens and goes at once when it
  closes. UseLightDismissOverlayMode dims the content with the theme overlay.
-->
<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:uikit="using:AvaloniaUIKit">
  <!-- shadow_xl (gpui styles.rs): (0, 20) blur 25 spread -5, (0, 8) blur 10 spread -6, black at 10%. -->
  <BoxShadows x:Key="UIKit.Shadow.Xl">0 20 84.8705 -5 #1A000000, 0 8 32.909 -6 #1A000000</BoxShadows>
  <!-- SheetSettings.margin_top: the sheet's offset below a custom title bar (GPUI: 34px, TITLE_BAR_HEIGHT). -->
  <Thickness x:Key="UIKit.Sheet.Margin">0</Thickness>

  <ControlTheme x:Key="{x:Type SplitView}" TargetType="SplitView">
    <Setter Property="OpenPaneLength" Value="255" />
    <Setter Property="CompactPaneLength" Value="48" />
    <Setter Property="PaneBackground" Value="{DynamicResource UIKit.Sidebar}" />
''')
for side in SIDES:
    w(f'''    <Style Selector="^:{side}">
{template(side)}
{spans(side)}
    </Style>''')
w('')
w('    <!-- The pane: open, the open length; closed, the closed length of the mode. -->')
for axis, sides, prop, closed in [("Width", ("left", "right"), "Width", "ClosedPaneWidth"), ("Height", ("top", "bottom"), "Height", "ClosedPaneHeight")]:
    sel_open = ", ".join(f"^:{s}:open /template/ Panel#PART_PaneRoot" for s in sides)
    sel_closed = ", ".join(f"^:{s}:closed /template/ Panel#PART_PaneRoot" for s in sides)
    w(f'''    <Style Selector="{sel_open}">
      <Setter Property="{prop}" Value="{{Binding $parent[SplitView].OpenPaneLength}}" />
    </Style>
    <Style Selector="{sel_closed}">
      <Setter Property="{prop}" Value="{{Binding $parent[SplitView].TemplateSettings.{closed}}}" />
    </Style>''')
    modes = ", ".join(f"^:{s}:{m} /template/ Panel#PART_PaneRoot" for s in sides for m in ("inline", "compactinline", "compactoverlay"))
    w(f'''    <!-- mod.rs: EffectTransition 200ms ease_in_out_cubic on the clip; not on the first layout. -->
    <Style Selector="{modes}">
      <Setter Property="uikit:Motion.SettledTransitions">
        <Transitions>
          <DoubleTransition Property="{prop}" Duration="0:0:0.2" Easing="CubicEaseInOut" />
        </Transitions>
      </Setter>
    </Style>''')
w('')
w('    <!-- The surface: its own width, snapping, and the border on the content side. -->')
for side in SIDES:
    horizontal = side in ("left", "right")
    prop = "Width" if horizontal else "Height"
    align = "HorizontalAlignment" if horizontal else "VerticalAlignment"
    w(f'''    <Style Selector="^:{side} /template/ Border#PART_PaneSurface">
      <Setter Property="BorderThickness" Value="{BORDER[side]}" />
    </Style>
    <Style Selector="^:{side}:compactinline /template/ Border#PART_PaneSurface, ^:{side}:compactoverlay /template/ Border#PART_PaneSurface">
      <Setter Property="{align}" Value="{EDGE[side]}" />
      <Setter Property="{prop}" Value="{{Binding $parent[SplitView].OpenPaneLength}}" />
    </Style>
    <Style Selector="^:{side}:compactinline:closed /template/ Border#PART_PaneSurface, ^:{side}:compactoverlay:closed /template/ Border#PART_PaneSurface">
      <Setter Property="{prop}" Value="{{Binding $parent[SplitView].CompactPaneLength}}" />
    </Style>
    <Style Selector="^:{side}:inline /template/ Border#PART_PaneSurface">
      <Setter Property="{align}" Value="{INWARD[side]}" />
      <Setter Property="{prop}" Value="{{Binding $parent[SplitView].OpenPaneLength}}" />
    </Style>''')
w('')
w('''    <!--
      Overlay: the sheet. The pane sits below UIKit.Sheet.Margin and slides
      100px in from its edge over 150ms, linearly (sheet.rs), its shadow
      spilling past it; closing collapses it at once. Closed, it is collapsed
      rather than hidden, so DrawerPage can focus into it as it opens.
    -->
    <Style Selector="^:overlay">
      <Setter Property="PaneBackground" Value="{DynamicResource UIKit.Background}" />
    </Style>
    <Style Selector="^:overlay /template/ Panel#PART_PaneRoot">
      <Setter Property="Margin" Value="{DynamicResource UIKit.Sheet.Margin}" />
    </Style>
    <Style Selector="^:overlay:open /template/ Panel#PART_PaneRoot">
      <Setter Property="ClipToBounds" Value="False" />
    </Style>
    <Style Selector="^:overlay /template/ Border#PART_PaneSurface">
      <Setter Property="BorderBrush" Value="{DynamicResource UIKit.Border}" />
      <Setter Property="TextElement.Foreground" Value="{DynamicResource UIKit.Foreground}" />
    </Style>
    <Style Selector="^:overlay /template/ Border#PART_PaneShadow">
      <Setter Property="BoxShadow" Value="{StaticResource UIKit.Shadow.Xl}" />
    </Style>
    <Style Selector="^:bottom:overlay /template/ Panel#PART_PaneRoot">
      <Setter Property="Margin" Value="0" />
    </Style>''')
for side in SIDES:
    prop = "TranslateTransform.X" if side in ("left", "right") else "TranslateTransform.Y"
    start = {"left": -100, "right": 100, "top": -100, "bottom": 100}[side]
    w(f'''    <Style Selector="^:{side}:overlay:open /template/ Panel#PART_PaneRoot">
      <Style.Animations>
        <Animation Duration="0:0:0.15">
          <KeyFrame Cue="0%">
            <Setter Property="{prop}" Value="{start}" />
          </KeyFrame>
          <KeyFrame Cue="100%">
            <Setter Property="{prop}" Value="0" />
          </KeyFrame>
        </Animation>
      </Style.Animations>
    </Style>''')
w('''
    <Style Selector="^:lightDismiss /template/ Rectangle#LightDismissLayer">
      <Setter Property="Fill" Value="{DynamicResource UIKit.Overlay}" />
    </Style>
    <Style Selector="^:overlay:open /template/ Rectangle#LightDismissLayer, ^:compactoverlay:open /template/ Rectangle#LightDismissLayer">
      <Setter Property="IsVisible" Value="True" />
    </Style>
  </ControlTheme>
</ResourceDictionary>''')
OUT.write_text("\n".join(lines) + "\n")
print("wrote", OUT)
