#!/usr/bin/env python3
"""Generates src/AvaloniaUIKit/Themes/Controls/SplitButton.axaml.

GPUI Kit DropdownButton (crates/component/src/button/dropdown_button.rs) is two
Buttons side by side: the action, with its left corners rounded, and a square
caret button with its right corners rounded and no left edge. Both take the
DropdownButton's variant, outline and size; a ghost split lights the idle half
at half the hover background while the other half is hovered (hover_group).
The colors are the Button's (Gpui.Button.<Variant>[.Outline].<State>.*).
"""
from pathlib import Path
import importlib.util

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("button", ROOT / "scripts/gen_button_theme.py")
OUT = ROOT / "src/AvaloniaUIKit/Themes/Controls/SplitButton.axaml"

VARIANTS = ["default", "primary", "secondary", "danger", "warning", "success", "info", "ghost", "link", "text"]
# height, padding, text, square, caret (Caret: XS 12, S 14, else 16)
SIZES = {
    "xsmall": (20, 4, 12, 20, 12),
    "small": (24, 8, 14, 24, 14),
    "medium": (32, 10, 14, 32, 16),
    "large": (32, 12, 16, 32, 16),
}
R = 6.0
RING = 3.0


def pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in name.replace("-", "_").split("_"))


def key(variant, outline, state, part):
    return f"Gpui.Button.{pascal(variant)}{'.Outline' if outline else ''}.{pascal(state)}.{part}"


def num(v):
    return f"{v:g}"


def sel(variant, outline):
    s = "^"
    if variant != "default":
        s += f".{variant}"
    if outline:
        s += ".outline"
    return s


lines = []
w = lines.append
w("<!--")
w("  DO NOT EDIT. Generated by scripts/gen_split_theme.py.")
w("")
w("  GPUI Kit DropdownButton -> SplitButton (crates/component/src/button/dropdown_button.rs).")
w("  Classes: the Button's variants, outline and sizes (xsmall small large).")
w("  The flyout opens below the right edge in GPUI (Anchor::TopRight): give the")
w("  SplitButton's MenuFlyout Placement=\"BottomEdgeAlignedRight\".")
w("  Avalonia focuses a SplitButton as one stop; its ring shows on the action half,")
w("  where GPUI's first Tab lands.")
w("-->")
w('<ResourceDictionary xmlns="https://github.com/avaloniaui"')
w('                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
w('  <ControlTheme x:Key="GpuiSplitButtonPart" TargetType="Button">')
w('    <Setter Property="ClipToBounds" Value="False" />')
w('    <Setter Property="HorizontalContentAlignment" Value="Center" />')
w('    <Setter Property="VerticalContentAlignment" Value="Center" />')
w('    <Setter Property="Template">')
w('      <ControlTemplate>')
w('        <Panel>')
w('          <ContentPresenter Name="PART_ContentPresenter" BackgroundSizing="OuterBorderEdge"')
w('                            Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}"')
w('                            BorderThickness="{TemplateBinding BorderThickness}" CornerRadius="{TemplateBinding CornerRadius}"')
w('                            Padding="{TemplateBinding Padding}" Content="{TemplateBinding Content}"')
w('                            ContentTemplate="{TemplateBinding ContentTemplate}"')
w('                            HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"')
w('                            VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"')
w('                            Foreground="{TemplateBinding Foreground}"')
w('                            TextWrapping="NoWrap" RecognizesAccessKey="True" />')
w(f'          <Border Name="PART_FocusRing" Margin="-{num(RING)}" BorderThickness="{num(RING)}"')
w(f'                  CornerRadius="{num(R + RING / 2)},{num(RING / 2)},{num(RING / 2)},{num(R + RING / 2)}"')
w('                  BorderBrush="{DynamicResource Gpui.FocusRing}" IsVisible="False" IsHitTestVisible="False" />')
w('        </Panel>')
w('      </ControlTemplate>')
w('    </Setter>')
w('    <!-- The SplitButton marks the focused half through Tag, as a theme may not reach into a nested template. -->')
w('    <Style Selector="^[Tag=focus-ring] /template/ Border#PART_FocusRing">')
w('      <Setter Property="IsVisible" Value="True" />')
w('    </Style>')
w('  </ControlTheme>')
w('')
w('  <ControlTheme x:Key="{x:Type SplitButton}" TargetType="SplitButton">')
w('    <Setter Property="FontSize" Value="14" />')
w('    <Setter Property="ClipToBounds" Value="False" />')
w('    <Setter Property="Focusable" Value="True" />')
w('    <Setter Property="KeyboardNavigation.IsTabStop" Value="True" />')
w('    <Setter Property="HorizontalAlignment" Value="Left" />')
w('    <Setter Property="VerticalAlignment" Value="Top" />')
w('    <Setter Property="Template">')
w('      <ControlTemplate>')
w('        <StackPanel Orientation="Horizontal">')
w('          <Button Name="PART_PrimaryButton" Theme="{StaticResource GpuiSplitButtonPart}"')
w('                  Content="{TemplateBinding Content}" ContentTemplate="{TemplateBinding ContentTemplate}"')
w('                  Command="{TemplateBinding Command}" CommandParameter="{TemplateBinding CommandParameter}"')
w('                  FontSize="{TemplateBinding FontSize}"')
w('                  Focusable="False" KeyboardNavigation.IsTabStop="False" />')
w('          <Button Name="PART_SecondaryButton" Theme="{StaticResource GpuiSplitButtonPart}"')
w('                  Padding="0" Focusable="False" KeyboardNavigation.IsTabStop="False">')
w('            <PathIcon Name="PART_Caret" Data="{StaticResource Gpui.Icon.ChevronDown}" />')
w('          </Button>')
w('        </StackPanel>')
w('      </ControlTemplate>')
w('    </Setter>')
w('')

# Sizes (medium first so the size classes win).
for size, (h, px, text, square, caret) in sorted(SIZES.items(), key=lambda i: i[0] != "medium"):
    base = "^" if size == "medium" else f"^.{size}"
    if size != "medium":
        w(f'    <Style Selector="{base}">')
        w(f'      <Setter Property="FontSize" Value="{text}" />')
        w('    </Style>')
    w(f'    <Style Selector="{base} /template/ Button#PART_PrimaryButton">')
    w(f'      <Setter Property="Height" Value="{h}" />')
    w(f'      <Setter Property="Padding" Value="{px},0" />')
    w('    </Style>')

    w(f'    <Style Selector="{base} /template/ Button#PART_SecondaryButton">')
    w(f'      <Setter Property="Width" Value="{square}" />')
    w(f'      <Setter Property="Height" Value="{square}" />')
    w('    </Style>')
    w(f'    <Style Selector="{base} /template/ PathIcon#PART_Caret">')
    w(f'      <Setter Property="Width" Value="{caret}" />')
    w(f'      <Setter Property="Height" Value="{caret}" />')
    w('    </Style>')
w('')

for variant in VARIANTS:
    for outline in [False, True]:
        s = sel(variant, outline)
        t = 1 if (variant == "default" or outline) else 0
        r = R - t / 2
        w(f'    <!-- {variant}{" outline" if outline else ""} -->')
        w(f'    <Style Selector="{s} /template/ Button#PART_PrimaryButton">')
        w(f'      <Setter Property="BorderThickness" Value="{t}" />')
        w(f'      <Setter Property="CornerRadius" Value="{num(r)},0,0,{num(r)}" />')
        w('    </Style>')
        w(f'    <Style Selector="{s} /template/ Button#PART_SecondaryButton">')
        w(f'      <Setter Property="BorderThickness" Value="0,{t},{t},{t}" />')
        w(f'      <Setter Property="CornerRadius" Value="0,{num(r)},{num(r)},0" />')
        w('    </Style>')
        w(f'    <Style Selector="{s} /template/ PathIcon#PART_Caret">')
        w(f'      <Setter Property="Foreground" Value="{{DynamicResource {key(variant, outline, "normal", "Caret").replace(".Normal.Caret", ".Caret")}}}" />')
        w('    </Style>')
        states = [
            ("normal", f"{s} /template/ Button"),
        ]
        if variant == "ghost":
            # hover_group: an idle half shows the hover background at 50%.
            states.append(("group-hover", f"{s}:pointerover /template/ Button, {s}:flyout-open /template/ Button#PART_PrimaryButton"))
        states += [
            ("hover", f"{s} /template/ Button:pointerover"),
            ("pressed", f"{s} /template/ Button:pressed"),
            ("selected", f"{s}.selected /template/ Button, {s}:flyout-open /template/ Button#PART_SecondaryButton"),
            ("disabled", f"{s}:disabled /template/ Button"),
        ]
        for state, selector in states:
            w(f'    <Style Selector="{selector}">')
            if state == "group-hover":
                w(f'      <Setter Property="Background" Value="{{DynamicResource {key(variant, outline, "group-hover", "Background")}}}" />')
            else:
                w(f'      <Setter Property="Background" Value="{{DynamicResource {key(variant, outline, state, "Background")}}}" />')
                w(f'      <Setter Property="Foreground" Value="{{DynamicResource {key(variant, outline, state, "Foreground")}}}" />')
                w(f'      <Setter Property="BorderBrush" Value="{{DynamicResource {key(variant, outline, state, "Border")}}}" />')
            w('    </Style>')
w('')
w('    <Style Selector="^:focus-visible /template/ Button#PART_PrimaryButton">')
w('      <Setter Property="BorderBrush" Value="{DynamicResource Gpui.Ring}" />')
w('    </Style>')
w('    <Style Selector="^:focus-visible /template/ Button#PART_PrimaryButton">')
w('      <Setter Property="Tag" Value="focus-ring" />')
w('    </Style>')
w('  </ControlTheme>')
w('</ResourceDictionary>')
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
