#!/usr/bin/env python3
"""Generates src/AvaloniaUIKit/Themes/Controls/Button.axaml.

GPUI Kit's Button (crates/component/src/button/button.rs) has ten variants,
an outline modifier and five visual states, each with its own background,
foreground and border color. XAML cannot compute resource keys, so every
combination is written out here. The colors themselves are generated from
GPUI Kit by `reference generate` (Gpui.Button.<Variant>[.Outline].<State>.*).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/AvaloniaUIKit/Themes/Controls/Button.axaml"

VARIANTS = ["default", "primary", "secondary", "danger", "warning", "success", "info", "ghost", "link", "text"]
# (state name in the generated keys, selector suffix)
STATES = [
    ("normal", ""),
    ("hover", ":pointerover"),
    ("pressed", ":pressed"),
    ("selected", ".selected"),
    ("disabled", ":disabled"),
]
# Size: height, horizontal padding, compact padding, compact min width, text size, square size
# (button.rs Button::render; sizing.rs button_text_size).
SIZES = {
    "xsmall": (20, 4, 4, 20, 12, 20),
    "small": (24, 8, 6, 24, 14, 24),
    "medium": (32, 10, 8, 32, 14, 32),
    "large": (32, 12, 8, 32, 16, 32),
}
# ButtonRounded: None, Small (radius * 0.5), Medium (radius), Large (radius * 2).
ROUNDED = {"none": 0.0, "small": 3.0, "medium": 6.0, "large": 12.0}
RING = 3.0  # FOCUS_RING_WIDTH (styled.rs)


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_"))


def key(variant: str, outline: bool, state: str, part: str) -> str:
    outline_part = ".Outline" if outline else ""
    return f"Gpui.Button.{pascal(variant)}{outline_part}.{pascal(state)}.{part}"


def bordered(variant: str, outline: bool) -> bool:
    # Only Default and outline buttons draw a 1px border (button.rs, `border_l_1()` etc.).
    return variant == "default" or outline


def num(value: float) -> str:
    return f"{value:g}"


def radius(r: float, border: float) -> str:
    # Avalonia (WinUI) corner radii sit on the middle of the border, so the
    # outer radius GPUI paints is CornerRadius + border / 2.
    if r == 0:
        return "0"
    return num(r - border / 2)


def selector(variant: str, outline: bool) -> str:
    parts = "^"
    if variant != "default":
        parts += f".{variant}"
    if outline:
        parts += ".outline"
    return parts


lines: list[str] = []
w = lines.append

w("<!--")
w("  DO NOT EDIT. Generated by scripts/gen_button_theme.py.")
w("")
w("  GPUI Kit Button -> Button (crates/component/src/button/button.rs).")
w("  Classes: variant  primary secondary danger warning success info ghost link text")
w("           modifier outline compact selected icon-only")
w("           size     xsmall small large (medium is the default)")
w("           corners  rounded-none rounded-small rounded-large")
w("  The focus ring shows on keyboard focus only (:focus-visible), as GPUI Kit")
w("  prevents a pointer press from focusing a button.")
w("-->")
w('<ResourceDictionary xmlns="https://github.com/avaloniaui"')
w('                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
w('  <ControlTheme x:Key="{x:Type Button}" TargetType="Button">')
w(f'    <Setter Property="Background" Value="{{DynamicResource {key("default", False, "normal", "Background")}}}" />')
w(f'    <Setter Property="Foreground" Value="{{DynamicResource {key("default", False, "normal", "Foreground")}}}" />')
w(f'    <Setter Property="BorderBrush" Value="{{DynamicResource {key("default", False, "normal", "Border")}}}" />')
w('    <Setter Property="BorderThickness" Value="1" />')
w(f'    <Setter Property="CornerRadius" Value="{radius(ROUNDED["medium"], 1)}" />')
h, px, _, _, text, _ = SIZES["medium"]
w(f'    <Setter Property="Height" Value="{h}" />')
w(f'    <Setter Property="Padding" Value="{px},0" />')
w(f'    <Setter Property="FontSize" Value="{text}" />')
w('    <!-- The focus ring is painted outside the bounds. -->')
w('    <Setter Property="ClipToBounds" Value="False" />')
w('    <Setter Property="HorizontalContentAlignment" Value="Center" />')
w('    <Setter Property="VerticalContentAlignment" Value="Center" />')
w('    <Setter Property="Template">')
w('      <ControlTemplate>')
w('        <Panel>')
w('          <ContentPresenter Name="PART_ContentPresenter"')
w('                            BackgroundSizing="OuterBorderEdge"')
w('                            Background="{TemplateBinding Background}"')
w('                            BorderBrush="{TemplateBinding BorderBrush}"')
w('                            BorderThickness="{TemplateBinding BorderThickness}"')
w('                            CornerRadius="{TemplateBinding CornerRadius}"')
w('                            Padding="{TemplateBinding Padding}"')
w('                            Content="{TemplateBinding Content}"')
w('                            ContentTemplate="{TemplateBinding ContentTemplate}"')
w('                            HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"')
w('                            VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"')
w('                            Foreground="{TemplateBinding Foreground}"')
w(f'                            LineHeight="{num(text * 1.25)}"')
w('                            TextWrapping="NoWrap"')
w('                            TextTrimming="CharacterEllipsis"')
w('                            RecognizesAccessKey="True" />')
w('          <!-- focus_ring (styled.rs): a 3px band outside the border, in ring at 50%. -->')
w(f'          <Border Name="PART_FocusRing" Margin="-{num(RING)}" BorderThickness="{num(RING)}"')
w(f'                  CornerRadius="{num(ROUNDED["medium"] + RING - RING / 2)}"')
w('                  BorderBrush="{DynamicResource Gpui.FocusRing}"')
w('                  IsVisible="False" IsHitTestVisible="False" />')
w('        </Panel>')
w('      </ControlTemplate>')
w('    </Setter>')
w('')

# Sizes, then the compact and square variants of each size.
for size, (h, px, cpx, cmin, text, square) in SIZES.items():
    sel = "^" if size == "medium" else f"^.{size}"
    if size != "medium":
        w(f'    <Style Selector="{sel}">')
        w(f'      <Setter Property="Height" Value="{h}" />')
        w(f'      <Setter Property="Padding" Value="{px},0" />')
        w(f'      <Setter Property="FontSize" Value="{text}" />')
        w('    </Style>')
        w(f'    <Style Selector="{sel} /template/ ContentPresenter#PART_ContentPresenter">')
        w(f'      <Setter Property="LineHeight" Value="{num(text * 1.25)}" />')
        w('    </Style>')
for size, (h, px, cpx, cmin, text, square) in SIZES.items():
    sel = "^.compact" if size == "medium" else f"^.compact.{size}"
    w(f'    <Style Selector="{sel}">')
    w(f'      <Setter Property="Padding" Value="{cpx},0" />')
    w(f'      <Setter Property="MinWidth" Value="{cmin}" />')
    w('    </Style>')
for size, (h, px, cpx, cmin, text, square) in SIZES.items():
    sel = "^.icon-only" if size == "medium" else f"^.icon-only.{size}"
    w(f'    <Style Selector="{sel}">')
    w(f'      <Setter Property="Width" Value="{square}" />')
    w(f'      <Setter Property="Height" Value="{square}" />')
    w('      <Setter Property="Padding" Value="0" />')
    w('    </Style>')
w('    <!-- Link and Text buttons have no height or padding (ButtonVariant::no_padding). -->')
for variant in ["link", "text"]:
    w(f'    <Style Selector="^.{variant}">')
    w('      <Setter Property="Height" Value="NaN" />')
    w('      <Setter Property="Padding" Value="0" />')
    w('      <Setter Property="MinWidth" Value="0" />')
    w('    </Style>')
w('    <!-- A link is underlined only in its normal look: GPUI skips the underline when disabled or selected. -->')
w('    <Style Selector="^.link /template/ ContentPresenter#PART_ContentPresenter">')
w('      <Setter Property="TextBlock.TextDecorations" Value="Underline" />')
w('    </Style>')
w('    <Style Selector="^.link:disabled /template/ ContentPresenter#PART_ContentPresenter, ^.link.selected /template/ ContentPresenter#PART_ContentPresenter">')
w('      <Setter Property="TextBlock.TextDecorations" Value="{x:Null}" />')
w('    </Style>')
w('')

# Colors: each (variant, outline) block defines every state, so the last
# matching block always wins regardless of the classes it shares with others.
for variant in VARIANTS:
    for outline in [False, True]:
        base = selector(variant, outline)
        border = 1 if bordered(variant, outline) else 0
        w(f'    <!-- {variant}{" outline" if outline else ""} -->')
        for state, suffix in STATES:
            sel = base if (state == "normal") else f"{base}{suffix}"
            w(f'    <Style Selector="{sel}">')
            w(f'      <Setter Property="Background" Value="{{DynamicResource {key(variant, outline, state, "Background")}}}" />')
            w(f'      <Setter Property="Foreground" Value="{{DynamicResource {key(variant, outline, state, "Foreground")}}}" />')
            w(f'      <Setter Property="BorderBrush" Value="{{DynamicResource {key(variant, outline, state, "Border")}}}" />')
            if state == "normal":
                w(f'      <Setter Property="BorderThickness" Value="{border}" />')
                w(f'      <Setter Property="CornerRadius" Value="{radius(ROUNDED["medium"], border)}" />')
            w('    </Style>')
        for rounded, r in ROUNDED.items():
            if rounded == "medium":
                continue
            w(f'    <Style Selector="{base}.rounded-{rounded}">')
            w(f'      <Setter Property="CornerRadius" Value="{radius(r, border)}" />')
            w('    </Style>')
w('')
w('    <!-- Selected keeps its look while hovered or pressed: GPUI registers no hover style on it. -->')
for variant in VARIANTS:
    for outline in [False, True]:
        base = selector(variant, outline)
        w(f'    <Style Selector="{base}.selected:pointerover, {base}.selected:pressed">')
        w(f'      <Setter Property="Background" Value="{{DynamicResource {key(variant, outline, "selected", "Background")}}}" />')
        w(f'      <Setter Property="Foreground" Value="{{DynamicResource {key(variant, outline, "selected", "Foreground")}}}" />')
        w(f'      <Setter Property="BorderBrush" Value="{{DynamicResource {key(variant, outline, "selected", "Border")}}}" />')
        w('    </Style>')
w('')
w('    <!-- Keyboard focus: the border turns to ring, and the ring band shows. -->')
w('    <Style Selector="^:focus-visible">')
w('      <Setter Property="BorderBrush" Value="{DynamicResource Gpui.Ring}" />')
w('    </Style>')
w('    <Style Selector="^:focus-visible /template/ Border#PART_FocusRing">')
w('      <Setter Property="IsVisible" Value="True" />')
w('    </Style>')
for rounded, r in ROUNDED.items():
    if rounded == "medium":
        continue
    w(f'    <Style Selector="^.rounded-{rounded} /template/ Border#PART_FocusRing">')
    w(f'      <Setter Property="CornerRadius" Value="{num(r + RING - RING / 2)}" />')
    w('    </Style>')
w('  </ControlTheme>')
w('</ResourceDictionary>')

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
