<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AvaloniaUIKit.Previews</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Skia" />
    <ProjectReference Include="../AvaloniaUIKit.Demos/AvaloniaUIKit.Demos.csproj" />
  </ItemGroup>
</Project>
